// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: Connection.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Peer information
type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Multiaddr     string                 `protobuf:"bytes,2,opt,name=multiaddr,proto3" json:"multiaddr,omitempty"`
	HeartbeatFail int32                  `protobuf:"varint,3,opt,name=heartbeat_fail,json=heartbeatFail,proto3" json:"heartbeat_fail,omitempty"`
	IsAlive       bool                   `protobuf:"varint,4,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	LastSeen      string                 `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_Connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{0}
}

func (x *Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peer) GetMultiaddr() string {
	if x != nil {
		return x.Multiaddr
	}
	return ""
}

func (x *Peer) GetHeartbeatFail() int32 {
	if x != nil {
		return x.HeartbeatFail
	}
	return 0
}

func (x *Peer) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *Peer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Peer) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

type PeerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerList) Reset() {
	*x = PeerList{}
	mi := &file_Connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerList) ProtoMessage() {}

func (x *PeerList) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerList.ProtoReflect.Descriptor instead.
func (*PeerList) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{1}
}

func (x *PeerList) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

// Message statistics
type MessageStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessagesSent     int64                  `protobuf:"varint,1,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	MessagesReceived int64                  `protobuf:"varint,2,opt,name=messages_received,json=messagesReceived,proto3" json:"messages_received,omitempty"`
	MessagesFailed   int64                  `protobuf:"varint,3,opt,name=messages_failed,json=messagesFailed,proto3" json:"messages_failed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageStats) Reset() {
	*x = MessageStats{}
	mi := &file_Connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStats) ProtoMessage() {}

func (x *MessageStats) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStats.ProtoReflect.Descriptor instead.
func (*MessageStats) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{2}
}

func (x *MessageStats) GetMessagesSent() int64 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

func (x *MessageStats) GetMessagesReceived() int64 {
	if x != nil {
		return x.MessagesReceived
	}
	return 0
}

func (x *MessageStats) GetMessagesFailed() int64 {
	if x != nil {
		return x.MessagesFailed
	}
	return 0
}

// Database state
type DatabaseState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          uint64                 `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	TxHash        []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseState) Reset() {
	*x = DatabaseState{}
	mi := &file_Connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseState) ProtoMessage() {}

func (x *DatabaseState) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseState.ProtoReflect.Descriptor instead.
func (*DatabaseState) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{3}
}

func (x *DatabaseState) GetTxId() uint64 {
	if x != nil {
		return x.TxId
	}
	return 0
}

func (x *DatabaseState) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *DatabaseState) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// DID Document
type DIDDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Balance       string                 `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Nonce         int64                  `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DIDDocument) Reset() {
	*x = DIDDocument{}
	mi := &file_Connection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DIDDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDDocument) ProtoMessage() {}

func (x *DIDDocument) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDDocument.ProtoReflect.Descriptor instead.
func (*DIDDocument) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{4}
}

func (x *DIDDocument) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *DIDDocument) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DIDDocument) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *DIDDocument) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DIDDocument) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *DIDDocument) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *DIDDocument) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DIDDocument) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Sync statistics
type SyncStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeTaken     int64                  `protobuf:"varint,1,opt,name=time_taken,json=timeTaken,proto3" json:"time_taken,omitempty"`
	MainState     *DatabaseState         `protobuf:"bytes,2,opt,name=main_state,json=mainState,proto3" json:"main_state,omitempty"`
	AccountsState *DatabaseState         `protobuf:"bytes,3,opt,name=accounts_state,json=accountsState,proto3" json:"accounts_state,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStats) Reset() {
	*x = SyncStats{}
	mi := &file_Connection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStats) ProtoMessage() {}

func (x *SyncStats) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStats.ProtoReflect.Descriptor instead.
func (*SyncStats) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{5}
}

func (x *SyncStats) GetTimeTaken() int64 {
	if x != nil {
		return x.TimeTaken
	}
	return 0
}

func (x *SyncStats) GetMainState() *DatabaseState {
	if x != nil {
		return x.MainState
	}
	return nil
}

func (x *SyncStats) GetAccountsState() *DatabaseState {
	if x != nil {
		return x.AccountsState
	}
	return nil
}

func (x *SyncStats) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Addrs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Peers         []string               `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Addrs) Reset() {
	*x = Addrs{}
	mi := &file_Connection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Addrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addrs) ProtoMessage() {}

func (x *Addrs) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addrs.ProtoReflect.Descriptor instead.
func (*Addrs) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{6}
}

func (x *Addrs) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Addrs) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Addrs) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request/Response messages
type PeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRequest) Reset() {
	*x = PeerRequest{}
	mi := &file_Connection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRequest) ProtoMessage() {}

func (x *PeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRequest.ProtoReflect.Descriptor instead.
func (*PeerRequest) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{7}
}

func (x *PeerRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_Connection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{8}
}

func (x *MessageRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Peer           string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Filepath       string                 `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	RemoteFilename string                 `protobuf:"bytes,3,opt,name=remote_filename,json=remoteFilename,proto3" json:"remote_filename,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_Connection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{9}
}

func (x *FileRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *FileRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *FileRequest) GetRemoteFilename() string {
	if x != nil {
		return x.RemoteFilename
	}
	return ""
}

type DIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DIDRequest) Reset() {
	*x = DIDRequest{}
	mi := &file_Connection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDRequest) ProtoMessage() {}

func (x *DIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDRequest.ProtoReflect.Descriptor instead.
func (*DIDRequest) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{10}
}

func (x *DIDRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type FirstSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // "server" or "client"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirstSyncRequest) Reset() {
	*x = FirstSyncRequest{}
	mi := &file_Connection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirstSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstSyncRequest) ProtoMessage() {}

func (x *FirstSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstSyncRequest.ProtoReflect.Descriptor instead.
func (*FirstSyncRequest) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{11}
}

func (x *FirstSyncRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *FirstSyncRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_Connection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{12}
}

func (x *OperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CleanPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CleanedCount  int32                  `protobuf:"varint,1,opt,name=cleaned_count,json=cleanedCount,proto3" json:"cleaned_count,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanPeersResponse) Reset() {
	*x = CleanPeersResponse{}
	mi := &file_Connection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanPeersResponse) ProtoMessage() {}

func (x *CleanPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanPeersResponse.ProtoReflect.Descriptor instead.
func (*CleanPeersResponse) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{13}
}

func (x *CleanPeersResponse) GetCleanedCount() int32 {
	if x != nil {
		return x.CleanedCount
	}
	return 0
}

func (x *CleanPeersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DatabaseStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainDb        *DatabaseState         `protobuf:"bytes,1,opt,name=main_db,json=mainDb,proto3" json:"main_db,omitempty"`
	AccountsDb    *DatabaseState         `protobuf:"bytes,2,opt,name=accounts_db,json=accountsDb,proto3" json:"accounts_db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseStates) Reset() {
	*x = DatabaseStates{}
	mi := &file_Connection_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseStates) ProtoMessage() {}

func (x *DatabaseStates) ProtoReflect() protoreflect.Message {
	mi := &file_Connection_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseStates.ProtoReflect.Descriptor instead.
func (*DatabaseStates) Descriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{14}
}

func (x *DatabaseStates) GetMainDb() *DatabaseState {
	if x != nil {
		return x.MainDb
	}
	return nil
}

func (x *DatabaseStates) GetAccountsDb() *DatabaseState {
	if x != nil {
		return x.AccountsDb
	}
	return nil
}

var File_Connection_proto protoreflect.FileDescriptor

const file_Connection_proto_rawDesc = "" +
	"\n" +
	"\x10Connection.proto\x12\x03cli\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tmultiaddr\x18\x02 \x01(\tR\tmultiaddr\x12%\n" +
	"\x0eheartbeat_fail\x18\x03 \x01(\x05R\rheartbeatFail\x12\x19\n" +
	"\bis_alive\x18\x04 \x01(\bR\aisAlive\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\tR\blastSeen\"+\n" +
	"\bPeerList\x12\x1f\n" +
	"\x05peers\x18\x01 \x03(\v2\t.cli.PeerR\x05peers\"\x89\x01\n" +
	"\fMessageStats\x12#\n" +
	"\rmessages_sent\x18\x01 \x01(\x03R\fmessagesSent\x12+\n" +
	"\x11messages_received\x18\x02 \x01(\x03R\x10messagesReceived\x12'\n" +
	"\x0fmessages_failed\x18\x03 \x01(\x03R\x0emessagesFailed\"Y\n" +
	"\rDatabaseState\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\x04R\x04txId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\fR\x06txHash\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\"\x94\x02\n" +
	"\vDIDDocument\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\abalance\x18\x03 \x01(\tR\abalance\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x03R\x05nonce\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xae\x01\n" +
	"\tSyncStats\x12\x1d\n" +
	"\n" +
	"time_taken\x18\x01 \x01(\x03R\ttimeTaken\x121\n" +
	"\n" +
	"main_state\x18\x02 \x01(\v2\x12.cli.DatabaseStateR\tmainState\x129\n" +
	"\x0eaccounts_state\x18\x03 \x01(\v2\x12.cli.DatabaseStateR\raccountsState\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"I\n" +
	"\x05Addrs\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05peers\x18\x02 \x03(\tR\x05peers\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"!\n" +
	"\vPeerRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\"B\n" +
	"\x0eMessageRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"f\n" +
	"\vFileRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12\x1a\n" +
	"\bfilepath\x18\x02 \x01(\tR\bfilepath\x12'\n" +
	"\x0fremote_filename\x18\x03 \x01(\tR\x0eremoteFilename\"\x1e\n" +
	"\n" +
	"DIDRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\":\n" +
	"\x10FirstSyncRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"G\n" +
	"\x11OperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x12CleanPeersResponse\x12#\n" +
	"\rcleaned_count\x18\x01 \x01(\x05R\fcleanedCount\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"r\n" +
	"\x0eDatabaseStates\x12+\n" +
	"\amain_db\x18\x01 \x01(\v2\x12.cli.DatabaseStateR\x06mainDb\x123\n" +
	"\vaccounts_db\x18\x02 \x01(\v2\x12.cli.DatabaseStateR\n" +
	"accountsDb2\xc1\x06\n" +
	"\n" +
	"CLIService\x124\n" +
	"\tListPeers\x12\x16.google.protobuf.Empty\x1a\r.cli.PeerList\"\x00\x125\n" +
	"\aAddPeer\x12\x10.cli.PeerRequest\x1a\x16.cli.OperationResponse\"\x00\x128\n" +
	"\n" +
	"RemovePeer\x12\x10.cli.PeerRequest\x1a\x16.cli.OperationResponse\"\x00\x12?\n" +
	"\n" +
	"CleanPeers\x12\x16.google.protobuf.Empty\x1a\x17.cli.CleanPeersResponse\"\x00\x12<\n" +
	"\vSendMessage\x12\x13.cli.MessageRequest\x1a\x16.cli.OperationResponse\"\x00\x12E\n" +
	"\x14SendYggdrasilMessage\x12\x13.cli.MessageRequest\x1a\x16.cli.OperationResponse\"\x00\x126\n" +
	"\bSendFile\x12\x10.cli.FileRequest\x1a\x16.cli.OperationResponse\"\x00\x12A\n" +
	"\x10BroadcastMessage\x12\x13.cli.MessageRequest\x1a\x16.cli.OperationResponse\"\x00\x12>\n" +
	"\x0fGetMessageStats\x12\x16.google.protobuf.Empty\x1a\x11.cli.MessageStats\"\x00\x12-\n" +
	"\x06GetDID\x12\x0f.cli.DIDRequest\x1a\x10.cli.DIDDocument\"\x00\x12.\n" +
	"\bFastSync\x12\x10.cli.PeerRequest\x1a\x0e.cli.SyncStats\"\x00\x124\n" +
	"\tFirstSync\x12\x15.cli.FirstSyncRequest\x1a\x0e.cli.SyncStats\"\x00\x12A\n" +
	"\x10GetDatabaseState\x12\x16.google.protobuf.Empty\x1a\x13.cli.DatabaseStates\"\x00\x123\n" +
	"\vReturnAddrs\x12\x16.google.protobuf.Empty\x1a\n" +
	".cli.Addrs\"\x00B\tZ\a./protob\x06proto3"

var (
	file_Connection_proto_rawDescOnce sync.Once
	file_Connection_proto_rawDescData []byte
)

func file_Connection_proto_rawDescGZIP() []byte {
	file_Connection_proto_rawDescOnce.Do(func() {
		file_Connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Connection_proto_rawDesc), len(file_Connection_proto_rawDesc)))
	})
	return file_Connection_proto_rawDescData
}

var file_Connection_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_Connection_proto_goTypes = []any{
	(*Peer)(nil),                  // 0: cli.Peer
	(*PeerList)(nil),              // 1: cli.PeerList
	(*MessageStats)(nil),          // 2: cli.MessageStats
	(*DatabaseState)(nil),         // 3: cli.DatabaseState
	(*DIDDocument)(nil),           // 4: cli.DIDDocument
	(*SyncStats)(nil),             // 5: cli.SyncStats
	(*Addrs)(nil),                 // 6: cli.Addrs
	(*PeerRequest)(nil),           // 7: cli.PeerRequest
	(*MessageRequest)(nil),        // 8: cli.MessageRequest
	(*FileRequest)(nil),           // 9: cli.FileRequest
	(*DIDRequest)(nil),            // 10: cli.DIDRequest
	(*FirstSyncRequest)(nil),      // 11: cli.FirstSyncRequest
	(*OperationResponse)(nil),     // 12: cli.OperationResponse
	(*CleanPeersResponse)(nil),    // 13: cli.CleanPeersResponse
	(*DatabaseStates)(nil),        // 14: cli.DatabaseStates
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 16: google.protobuf.Empty
}
var file_Connection_proto_depIdxs = []int32{
	0,  // 0: cli.PeerList.peers:type_name -> cli.Peer
	15, // 1: cli.DIDDocument.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: cli.DIDDocument.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 3: cli.SyncStats.main_state:type_name -> cli.DatabaseState
	3,  // 4: cli.SyncStats.accounts_state:type_name -> cli.DatabaseState
	3,  // 5: cli.DatabaseStates.main_db:type_name -> cli.DatabaseState
	3,  // 6: cli.DatabaseStates.accounts_db:type_name -> cli.DatabaseState
	16, // 7: cli.CLIService.ListPeers:input_type -> google.protobuf.Empty
	7,  // 8: cli.CLIService.AddPeer:input_type -> cli.PeerRequest
	7,  // 9: cli.CLIService.RemovePeer:input_type -> cli.PeerRequest
	16, // 10: cli.CLIService.CleanPeers:input_type -> google.protobuf.Empty
	8,  // 11: cli.CLIService.SendMessage:input_type -> cli.MessageRequest
	8,  // 12: cli.CLIService.SendYggdrasilMessage:input_type -> cli.MessageRequest
	9,  // 13: cli.CLIService.SendFile:input_type -> cli.FileRequest
	8,  // 14: cli.CLIService.BroadcastMessage:input_type -> cli.MessageRequest
	16, // 15: cli.CLIService.GetMessageStats:input_type -> google.protobuf.Empty
	10, // 16: cli.CLIService.GetDID:input_type -> cli.DIDRequest
	7,  // 17: cli.CLIService.FastSync:input_type -> cli.PeerRequest
	11, // 18: cli.CLIService.FirstSync:input_type -> cli.FirstSyncRequest
	16, // 19: cli.CLIService.GetDatabaseState:input_type -> google.protobuf.Empty
	16, // 20: cli.CLIService.ReturnAddrs:input_type -> google.protobuf.Empty
	1,  // 21: cli.CLIService.ListPeers:output_type -> cli.PeerList
	12, // 22: cli.CLIService.AddPeer:output_type -> cli.OperationResponse
	12, // 23: cli.CLIService.RemovePeer:output_type -> cli.OperationResponse
	13, // 24: cli.CLIService.CleanPeers:output_type -> cli.CleanPeersResponse
	12, // 25: cli.CLIService.SendMessage:output_type -> cli.OperationResponse
	12, // 26: cli.CLIService.SendYggdrasilMessage:output_type -> cli.OperationResponse
	12, // 27: cli.CLIService.SendFile:output_type -> cli.OperationResponse
	12, // 28: cli.CLIService.BroadcastMessage:output_type -> cli.OperationResponse
	2,  // 29: cli.CLIService.GetMessageStats:output_type -> cli.MessageStats
	4,  // 30: cli.CLIService.GetDID:output_type -> cli.DIDDocument
	5,  // 31: cli.CLIService.FastSync:output_type -> cli.SyncStats
	5,  // 32: cli.CLIService.FirstSync:output_type -> cli.SyncStats
	14, // 33: cli.CLIService.GetDatabaseState:output_type -> cli.DatabaseStates
	6,  // 34: cli.CLIService.ReturnAddrs:output_type -> cli.Addrs
	21, // [21:35] is the sub-list for method output_type
	7,  // [7:21] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_Connection_proto_init() }
func file_Connection_proto_init() {
	if File_Connection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Connection_proto_rawDesc), len(file_Connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Connection_proto_goTypes,
		DependencyIndexes: file_Connection_proto_depIdxs,
		MessageInfos:      file_Connection_proto_msgTypes,
	}.Build()
	File_Connection_proto = out.File
	file_Connection_proto_goTypes = nil
	file_Connection_proto_depIdxs = nil
}
