// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: gETH.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chain_GetBlockByNumber_FullMethodName     = "/gETH.Chain/GetBlockByNumber"
	Chain_GetBlockByHash_FullMethodName       = "/gETH.Chain/GetBlockByHash"
	Chain_GetTransactionByHash_FullMethodName = "/gETH.Chain/GetTransactionByHash"
	Chain_GetReceiptByHash_FullMethodName     = "/gETH.Chain/GetReceiptByHash"
	Chain_GetAccountState_FullMethodName      = "/gETH.Chain/GetAccountState"
	Chain_GetLogs_FullMethodName              = "/gETH.Chain/GetLogs"
	Chain_Call_FullMethodName                 = "/gETH.Chain/Call"
	Chain_EstimateGas_FullMethodName          = "/gETH.Chain/EstimateGas"
	Chain_SendRawTransaction_FullMethodName   = "/gETH.Chain/SendRawTransaction"
	Chain_StreamHeads_FullMethodName          = "/gETH.Chain/StreamHeads"
	Chain_StreamLogs_FullMethodName           = "/gETH.Chain/StreamLogs"
)

// ChainClient is the client API for Chain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Chain service definition
type ChainClient interface {
	// Block operations
	GetBlockByNumber(ctx context.Context, in *GetBlockByNumberReq, opts ...grpc.CallOption) (*Block, error)
	GetBlockByHash(ctx context.Context, in *GetBlockByHashReq, opts ...grpc.CallOption) (*Block, error)
	// Transaction operations
	GetTransactionByHash(ctx context.Context, in *GetByHashReq, opts ...grpc.CallOption) (*Transaction, error)
	GetReceiptByHash(ctx context.Context, in *GetByHashReq, opts ...grpc.CallOption) (*Receipt, error)
	// Account operations
	GetAccountState(ctx context.Context, in *GetAccountStateReq, opts ...grpc.CallOption) (*AccountState, error)
	// Logs and events
	GetLogs(ctx context.Context, in *GetLogsReq, opts ...grpc.CallOption) (*GetLogsResp, error)
	// Contract interaction
	Call(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*CallResp, error)
	EstimateGas(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*EstimateResp, error)
	// Transaction submission
	SendRawTransaction(ctx context.Context, in *SendRawTxReq, opts ...grpc.CallOption) (*SendRawTxResp, error)
	// Streaming
	StreamHeads(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockHeader], error)
	StreamLogs(ctx context.Context, in *LogsSubReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Log], error)
}

type chainClient struct {
	cc grpc.ClientConnInterface
}

func NewChainClient(cc grpc.ClientConnInterface) ChainClient {
	return &chainClient{cc}
}

func (c *chainClient) GetBlockByNumber(ctx context.Context, in *GetBlockByNumberReq, opts ...grpc.CallOption) (*Block, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Block)
	err := c.cc.Invoke(ctx, Chain_GetBlockByNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainClient) GetBlockByHash(ctx context.Context, in *GetBlockByHashReq, opts ...grpc.CallOption) (*Block, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Block)
	err := c.cc.Invoke(ctx, Chain_GetBlockByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainClient) GetTransactionByHash(ctx context.Context, in *GetByHashReq, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, Chain_GetTransactionByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainClient) GetReceiptByHash(ctx context.Context, in *GetByHashReq, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Chain_GetReceiptByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainClient) GetAccountState(ctx context.Context, in *GetAccountStateReq, opts ...grpc.CallOption) (*AccountState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountState)
	err := c.cc.Invoke(ctx, Chain_GetAccountState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainClient) GetLogs(ctx context.Context, in *GetLogsReq, opts ...grpc.CallOption) (*GetLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogsResp)
	err := c.cc.Invoke(ctx, Chain_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainClient) Call(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*CallResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResp)
	err := c.cc.Invoke(ctx, Chain_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainClient) EstimateGas(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*EstimateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateResp)
	err := c.cc.Invoke(ctx, Chain_EstimateGas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainClient) SendRawTransaction(ctx context.Context, in *SendRawTxReq, opts ...grpc.CallOption) (*SendRawTxResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendRawTxResp)
	err := c.cc.Invoke(ctx, Chain_SendRawTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainClient) StreamHeads(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockHeader], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chain_ServiceDesc.Streams[0], Chain_StreamHeads_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, BlockHeader]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chain_StreamHeadsClient = grpc.ServerStreamingClient[BlockHeader]

func (c *chainClient) StreamLogs(ctx context.Context, in *LogsSubReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Log], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chain_ServiceDesc.Streams[1], Chain_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsSubReq, Log]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chain_StreamLogsClient = grpc.ServerStreamingClient[Log]

// ChainServer is the server API for Chain service.
// All implementations must embed UnimplementedChainServer
// for forward compatibility.
//
// Chain service definition
type ChainServer interface {
	// Block operations
	GetBlockByNumber(context.Context, *GetBlockByNumberReq) (*Block, error)
	GetBlockByHash(context.Context, *GetBlockByHashReq) (*Block, error)
	// Transaction operations
	GetTransactionByHash(context.Context, *GetByHashReq) (*Transaction, error)
	GetReceiptByHash(context.Context, *GetByHashReq) (*Receipt, error)
	// Account operations
	GetAccountState(context.Context, *GetAccountStateReq) (*AccountState, error)
	// Logs and events
	GetLogs(context.Context, *GetLogsReq) (*GetLogsResp, error)
	// Contract interaction
	Call(context.Context, *CallReq) (*CallResp, error)
	EstimateGas(context.Context, *CallReq) (*EstimateResp, error)
	// Transaction submission
	SendRawTransaction(context.Context, *SendRawTxReq) (*SendRawTxResp, error)
	// Streaming
	StreamHeads(*Empty, grpc.ServerStreamingServer[BlockHeader]) error
	StreamLogs(*LogsSubReq, grpc.ServerStreamingServer[Log]) error
	mustEmbedUnimplementedChainServer()
}

// UnimplementedChainServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChainServer struct{}

func (UnimplementedChainServer) GetBlockByNumber(context.Context, *GetBlockByNumberReq) (*Block, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByNumber not implemented")
}
func (UnimplementedChainServer) GetBlockByHash(context.Context, *GetBlockByHashReq) (*Block, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByHash not implemented")
}
func (UnimplementedChainServer) GetTransactionByHash(context.Context, *GetByHashReq) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionByHash not implemented")
}
func (UnimplementedChainServer) GetReceiptByHash(context.Context, *GetByHashReq) (*Receipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReceiptByHash not implemented")
}
func (UnimplementedChainServer) GetAccountState(context.Context, *GetAccountStateReq) (*AccountState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountState not implemented")
}
func (UnimplementedChainServer) GetLogs(context.Context, *GetLogsReq) (*GetLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedChainServer) Call(context.Context, *CallReq) (*CallResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedChainServer) EstimateGas(context.Context, *CallReq) (*EstimateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateGas not implemented")
}
func (UnimplementedChainServer) SendRawTransaction(context.Context, *SendRawTxReq) (*SendRawTxResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRawTransaction not implemented")
}
func (UnimplementedChainServer) StreamHeads(*Empty, grpc.ServerStreamingServer[BlockHeader]) error {
	return status.Errorf(codes.Unimplemented, "method StreamHeads not implemented")
}
func (UnimplementedChainServer) StreamLogs(*LogsSubReq, grpc.ServerStreamingServer[Log]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedChainServer) mustEmbedUnimplementedChainServer() {}
func (UnimplementedChainServer) testEmbeddedByValue()               {}

// UnsafeChainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainServer will
// result in compilation errors.
type UnsafeChainServer interface {
	mustEmbedUnimplementedChainServer()
}

func RegisterChainServer(s grpc.ServiceRegistrar, srv ChainServer) {
	// If the following call pancis, it indicates UnimplementedChainServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chain_ServiceDesc, srv)
}

func _Chain_GetBlockByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServer).GetBlockByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chain_GetBlockByNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServer).GetBlockByNumber(ctx, req.(*GetBlockByNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chain_GetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHashReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServer).GetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chain_GetBlockByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServer).GetBlockByHash(ctx, req.(*GetBlockByHashReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chain_GetTransactionByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByHashReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServer).GetTransactionByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chain_GetTransactionByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServer).GetTransactionByHash(ctx, req.(*GetByHashReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chain_GetReceiptByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByHashReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServer).GetReceiptByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chain_GetReceiptByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServer).GetReceiptByHash(ctx, req.(*GetByHashReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chain_GetAccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServer).GetAccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chain_GetAccountState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServer).GetAccountState(ctx, req.(*GetAccountStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chain_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chain_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServer).GetLogs(ctx, req.(*GetLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chain_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chain_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServer).Call(ctx, req.(*CallReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chain_EstimateGas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServer).EstimateGas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chain_EstimateGas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServer).EstimateGas(ctx, req.(*CallReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chain_SendRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRawTxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServer).SendRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chain_SendRawTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServer).SendRawTransaction(ctx, req.(*SendRawTxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chain_StreamHeads_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChainServer).StreamHeads(m, &grpc.GenericServerStream[Empty, BlockHeader]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chain_StreamHeadsServer = grpc.ServerStreamingServer[BlockHeader]

func _Chain_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsSubReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChainServer).StreamLogs(m, &grpc.GenericServerStream[LogsSubReq, Log]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chain_StreamLogsServer = grpc.ServerStreamingServer[Log]

// Chain_ServiceDesc is the grpc.ServiceDesc for Chain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gETH.Chain",
	HandlerType: (*ChainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockByNumber",
			Handler:    _Chain_GetBlockByNumber_Handler,
		},
		{
			MethodName: "GetBlockByHash",
			Handler:    _Chain_GetBlockByHash_Handler,
		},
		{
			MethodName: "GetTransactionByHash",
			Handler:    _Chain_GetTransactionByHash_Handler,
		},
		{
			MethodName: "GetReceiptByHash",
			Handler:    _Chain_GetReceiptByHash_Handler,
		},
		{
			MethodName: "GetAccountState",
			Handler:    _Chain_GetAccountState_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _Chain_GetLogs_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _Chain_Call_Handler,
		},
		{
			MethodName: "EstimateGas",
			Handler:    _Chain_EstimateGas_Handler,
		},
		{
			MethodName: "SendRawTransaction",
			Handler:    _Chain_SendRawTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHeads",
			Handler:       _Chain_StreamHeads_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _Chain_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gETH.proto",
}
