package Structs

// Stage 5 tests, per docs/JMDN-CRDT-VOTE-MIGRATION-LLD.md §7.

import (
	"context"
	"testing"

	"gossipnode/AVC/BuddyNodes/DataLayer"
	"gossipnode/AVC/BuddyNodes/MessagePassing/BLS_Signer"
	PubSubMessages "gossipnode/config/PubSubMessages"

	avcvotes "github.com/JupiterMetaLabs/avc/crdt/votes"
	avctypes "github.com/JupiterMetaLabs/avc/types"
	"github.com/libp2p/go-libp2p/core/crypto"
	"github.com/libp2p/go-libp2p/core/peer"
)

const (
	stage5ChainID   = uint64(7000700)
	stage5Height    = uint64(9000)
	stage5BlockHash = "0xstage5"
)

func stage5TestPeer(t *testing.T) peer.ID {
	t.Helper()
	priv, _, err := crypto.GenerateKeyPair(crypto.Ed25519, 0)
	if err != nil {
		t.Fatalf("generating test identity: %v", err)
	}
	id, err := peer.IDFromPrivateKey(priv)
	if err != nil {
		t.Fatalf("deriving peer ID: %v", err)
	}
	return id
}

// stage5SignedRecord signs vote with this process's (autogenerated) BLS
// keypair — real material, so BLS_Verifier.VerifyForBlock genuinely checks
// it rather than trivially accepting a fixture.
func stage5SignedRecord(t *testing.T, peerID peer.ID, vote int8, height uint64, blockHash string) avcvotes.VoteRecord {
	t.Helper()
	blsResp, signed, err := BLS_Signer.SignMessageForBlock(vote, stage5ChainID, height, blockHash, "")
	if err != nil || !signed {
		t.Fatalf("SignMessageForBlock: signed=%v err=%v", signed, err)
	}
	return avcvotes.VoteRecord{
		PeerID:       peerID.String(),
		Vote:         vote,
		BlockHash:    blockHash,
		Height:       height,
		BLSSignature: blsResp.Signature,
		BLSPubKeyHex: blsResp.PubKey,
	}
}

// Exit criterion 1: aggregate verification passes on a real block through
// the new path — every validly signed (peer, value) pair survives intact.
func TestVerifyTallySignatures_ValidVotesSurviveIntact(t *testing.T) {
	t.Setenv("JMDN_BLS_AUTOGEN", "1")
	peerA := stage5TestPeer(t)
	peerB := stage5TestPeer(t)

	recA := stage5SignedRecord(t, peerA, 1, stage5Height, stage5BlockHash)
	recB := stage5SignedRecord(t, peerB, -1, stage5Height, stage5BlockHash)

	tally := avcvotes.BlockTally{
		AuthorizedVotesByPeer: map[string][]int8{
			peerA.String(): {1},
			peerB.String(): {-1},
		},
		Signatures: map[string][]avcvotes.VoteRecord{
			peerA.String(): {recA},
			peerB.String(): {recB},
		},
	}

	verified, dropped := verifyTallySignatures(tally, stage5ChainID, stage5Height, stage5BlockHash, "")
	if dropped != 0 {
		t.Fatalf("expected 0 dropped for two validly signed votes, got %d", dropped)
	}
	single := verified.SingleVotePeers()
	if len(single) != 2 || single[peerA.String()] != 1 || single[peerB.String()] != -1 {
		t.Fatalf("verified tally lost or altered a valid vote: %+v", single)
	}
}

// Exit criterion 2: a forged signature in the CRDT is rejected, and the
// vote is not counted.
func TestVerifyTallySignatures_ForgedSignatureIsDroppedAndNotCounted(t *testing.T) {
	t.Setenv("JMDN_BLS_AUTOGEN", "1")
	peerA := stage5TestPeer(t)
	peerForged := stage5TestPeer(t)

	recA := stage5SignedRecord(t, peerA, 1, stage5Height, stage5BlockHash)
	// Forged: a syntactically valid pubkey/signature pair, but the signature
	// was never produced by that pubkey's private key for this message.
	otherSigner, _, err := BLS_Signer.SignMessageForBlock(1, stage5ChainID, stage5Height, "0xdifferent-block", "")
	if err != nil {
		t.Fatalf("building a forged signature fixture: %v", err)
	}
	forged := avcvotes.VoteRecord{
		PeerID:       peerForged.String(),
		Vote:         -1,
		BlockHash:    stage5BlockHash,
		Height:       stage5Height,
		BLSSignature: otherSigner.Signature, // signs a different message entirely
		BLSPubKeyHex: otherSigner.PubKey,
	}

	tally := avcvotes.BlockTally{
		AuthorizedVotesByPeer: map[string][]int8{
			peerA.String():      {1},
			peerForged.String(): {-1},
		},
		Signatures: map[string][]avcvotes.VoteRecord{
			peerA.String():      {recA},
			peerForged.String(): {forged},
		},
	}

	verified, dropped := verifyTallySignatures(tally, stage5ChainID, stage5Height, stage5BlockHash, "")
	if dropped != 1 {
		t.Fatalf("expected exactly 1 dropped (the forged vote), got %d", dropped)
	}
	single := verified.SingleVotePeers()
	if _, ok := single[peerForged.String()]; ok {
		t.Fatal("forged vote must not be counted")
	}
	if got, ok := single[peerA.String()]; !ok || got != 1 {
		t.Fatalf("the genuinely signed vote must still be counted, got %+v", single)
	}
}

// "On an equivocation pair, verify both": a peer with two GENUINELY signed
// conflicting values must have BOTH survive (real equivocation, real
// evidence) — verification must not collapse it back down to one.
func TestVerifyTallySignatures_GenuineEquivocationPairBothSurvive(t *testing.T) {
	t.Setenv("JMDN_BLS_AUTOGEN", "1")
	peerA := stage5TestPeer(t)

	yes := stage5SignedRecord(t, peerA, 1, stage5Height, stage5BlockHash)
	no := stage5SignedRecord(t, peerA, -1, stage5Height, stage5BlockHash)

	tally := avcvotes.BlockTally{
		AuthorizedVotesByPeer: map[string][]int8{peerA.String(): {1, -1}},
		Signatures:            map[string][]avcvotes.VoteRecord{peerA.String(): {yes, no}},
	}

	verified, dropped := verifyTallySignatures(tally, stage5ChainID, stage5Height, stage5BlockHash, "")
	if dropped != 0 {
		t.Fatalf("both halves of a genuine equivocation are validly signed, expected 0 dropped, got %d", dropped)
	}
	if len(verified.EquivocatingPeers()) != 1 || verified.EquivocatingPeers()[0] != peerA.String() {
		t.Fatalf("expected peer to still be flagged as equivocating after verification, got %v", verified.EquivocatingPeers())
	}
}

// A forged SECOND value must not manufacture a false equivocation charge
// against a peer that genuinely cast only one real vote — the exact failure
// mode verifyTallySignatures exists to prevent, per the LLD's own caution.
func TestVerifyTallySignatures_ForgedSecondValueDoesNotManufactureEquivocation(t *testing.T) {
	t.Setenv("JMDN_BLS_AUTOGEN", "1")
	peerA := stage5TestPeer(t)

	realYes := stage5SignedRecord(t, peerA, 1, stage5Height, stage5BlockHash)
	otherSigner, _, err := BLS_Signer.SignMessageForBlock(1, stage5ChainID, stage5Height, "0xelsewhere", "")
	if err != nil {
		t.Fatalf("building a forged signature fixture: %v", err)
	}
	forgedNo := avcvotes.VoteRecord{
		PeerID:       peerA.String(),
		Vote:         -1,
		BlockHash:    stage5BlockHash,
		Height:       stage5Height,
		BLSSignature: otherSigner.Signature,
		BLSPubKeyHex: realYes.BLSPubKeyHex, // claims the real peer's own key
	}

	tally := avcvotes.BlockTally{
		AuthorizedVotesByPeer: map[string][]int8{peerA.String(): {1, -1}},
		Signatures:            map[string][]avcvotes.VoteRecord{peerA.String(): {realYes, forgedNo}},
	}

	verified, dropped := verifyTallySignatures(tally, stage5ChainID, stage5Height, stage5BlockHash, "")
	if dropped != 1 {
		t.Fatalf("expected exactly 1 dropped (the forged half), got %d", dropped)
	}
	if len(verified.EquivocatingPeers()) != 0 {
		t.Fatalf("a forged second value must not create an equivocation verdict, got %v", verified.EquivocatingPeers())
	}
	if got, ok := verified.SingleVotePeers()[peerA.String()]; !ok || got != 1 {
		t.Fatalf("the peer's one genuine vote must still count as a single valid vote, got %+v", verified.SingleVotePeers())
	}
}

// End-to-end through the actual new path (not just the helper in isolation):
// ProcessVotesFromCRDT with the flag on, a forged vote injected alongside a
// real one, must reach the same decision it would have without the forgery.
func TestProcessVotesFromCRDT_V2_ForgedVoteDoesNotFlipTheDecision(t *testing.T) {
	t.Setenv("JMDN_BLS_AUTOGEN", "1")
	origFlag := voteCRDTV2Enabled
	voteCRDTV2Enabled = true
	defer func() { voteCRDTV2Enabled = origFlag }()

	origFn := authorizedCommitteeFn
	defer func() { authorizedCommitteeFn = origFn }()

	peerYes1 := stage5TestPeer(t)
	peerYes2 := stage5TestPeer(t)
	peerForgedNo := stage5TestPeer(t)

	voteEngine := avctypes.Controller{CRDTLayer: DataLayer.NewVoteCRDTLayer(nil).CRDTLayer}

	// processVotesFromCRDT_v2 verifies against BLS_Signer.DomainChainID()
	// (the process's real configured/default chain id), not a test-chosen
	// constant — sign with the same value the code under test will actually
	// verify against, or every signature (including the genuine ones) fails
	// for an unrelated reason and this test would prove nothing.
	chainID := BLS_Signer.DomainChainID()
	sign := func(peerID peer.ID, vote int8) avcvotes.VoteRecord {
		blsResp, signed, err := BLS_Signer.SignMessageForBlock(vote, chainID, stage5Height, stage5BlockHash, "")
		if err != nil || !signed {
			t.Fatalf("SignMessageForBlock: signed=%v err=%v", signed, err)
		}
		return avcvotes.VoteRecord{
			PeerID: peerID.String(), Vote: vote, BlockHash: stage5BlockHash, Height: stage5Height,
			BLSSignature: blsResp.Signature, BLSPubKeyHex: blsResp.PubKey,
		}
	}

	recYes1 := sign(peerYes1, 1)
	recYes2 := sign(peerYes2, 1)
	if err := avcvotes.AddVote(&voteEngine, peerYes1, recYes1); err != nil {
		t.Fatalf("AddVote peerYes1: %v", err)
	}
	if err := avcvotes.AddVote(&voteEngine, peerYes2, recYes2); err != nil {
		t.Fatalf("AddVote peerYes2: %v", err)
	}

	// Inject a forged NO vote directly (bypassing AddVote's own signer, the
	// way a malicious or buggy peer's raw CRDT merge would land it).
	otherSigner, _, err := BLS_Signer.SignMessageForBlock(-1, chainID, stage5Height, "0xelsewhere", "")
	if err != nil {
		t.Fatalf("building a forged signature fixture: %v", err)
	}
	forgedRec := avcvotes.VoteRecord{
		PeerID:       peerForgedNo.String(),
		Vote:         -1,
		BlockHash:    stage5BlockHash,
		Height:       stage5Height,
		BLSSignature: otherSigner.Signature,
		BLSPubKeyHex: otherSigner.PubKey,
	}
	if err := avcvotes.AddVote(&voteEngine, peerForgedNo, forgedRec); err != nil {
		t.Fatalf("AddVote peerForgedNo: %v", err)
	}

	SetAuthorizedCommitteeFn(func() (map[string]string, error) {
		return map[string]string{
			peerYes1.String():     recYes1.BLSPubKeyHex,
			peerYes2.String():     recYes2.BLSPubKeyHex,
			peerForgedNo.String(): otherSigner.PubKey,
		}, nil
	})

	listenerNode := &PubSubMessages.BuddyNode{VoteCRDTLayer: &voteEngine}
	result, _, _, _, err := ProcessVotesFromCRDT(context.Background(), listenerNode, stage5BlockHash, stage5Height)
	if err != nil {
		t.Fatalf("ProcessVotesFromCRDT: %v", err)
	}
	if result != 1 {
		t.Fatalf("expected the 2 genuine YES votes to win (forged NO must not count), got %d", result)
	}
}
