// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: DID.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterDIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDIDRequest) Reset() {
	*x = RegisterDIDRequest{}
	mi := &file_DID_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDIDRequest) ProtoMessage() {}

func (x *RegisterDIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DID_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDIDRequest.ProtoReflect.Descriptor instead.
func (*RegisterDIDRequest) Descriptor() ([]byte, []int) {
	return file_DID_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDIDRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *RegisterDIDRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type RegisterDIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DidInfo       *DIDInfo               `protobuf:"bytes,3,opt,name=did_info,json=didInfo,proto3" json:"did_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDIDResponse) Reset() {
	*x = RegisterDIDResponse{}
	mi := &file_DID_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDIDResponse) ProtoMessage() {}

func (x *RegisterDIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DID_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDIDResponse.ProtoReflect.Descriptor instead.
func (*RegisterDIDResponse) Descriptor() ([]byte, []int) {
	return file_DID_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterDIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterDIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterDIDResponse) GetDidInfo() *DIDInfo {
	if x != nil {
		return x.DidInfo
	}
	return nil
}

type GetDIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDIDRequest) Reset() {
	*x = GetDIDRequest{}
	mi := &file_DID_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDIDRequest) ProtoMessage() {}

func (x *GetDIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DID_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDIDRequest.ProtoReflect.Descriptor instead.
func (*GetDIDRequest) Descriptor() ([]byte, []int) {
	return file_DID_proto_rawDescGZIP(), []int{2}
}

func (x *GetDIDRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type DIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	DidInfo       *DIDInfo               `protobuf:"bytes,2,opt,name=did_info,json=didInfo,proto3" json:"did_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DIDResponse) Reset() {
	*x = DIDResponse{}
	mi := &file_DID_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDResponse) ProtoMessage() {}

func (x *DIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DID_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDResponse.ProtoReflect.Descriptor instead.
func (*DIDResponse) Descriptor() ([]byte, []int) {
	return file_DID_proto_rawDescGZIP(), []int{3}
}

func (x *DIDResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *DIDResponse) GetDidInfo() *DIDInfo {
	if x != nil {
		return x.DidInfo
	}
	return nil
}

type DIDInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Balance       string                 `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce         string                 `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Metadata      string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AccountType   string                 `protobuf:"bytes,8,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DIDInfo) Reset() {
	*x = DIDInfo{}
	mi := &file_DID_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DIDInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDInfo) ProtoMessage() {}

func (x *DIDInfo) ProtoReflect() protoreflect.Message {
	mi := &file_DID_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDInfo.ProtoReflect.Descriptor instead.
func (*DIDInfo) Descriptor() ([]byte, []int) {
	return file_DID_proto_rawDescGZIP(), []int{4}
}

func (x *DIDInfo) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *DIDInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DIDInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DIDInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *DIDInfo) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *DIDInfo) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *DIDInfo) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *DIDInfo) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

type ListDIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDIDsRequest) Reset() {
	*x = ListDIDsRequest{}
	mi := &file_DID_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDIDsRequest) ProtoMessage() {}

func (x *ListDIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DID_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDIDsRequest.ProtoReflect.Descriptor instead.
func (*ListDIDsRequest) Descriptor() ([]byte, []int) {
	return file_DID_proto_rawDescGZIP(), []int{5}
}

func (x *ListDIDsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDIDsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListDIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dids          []*DIDInfo             `protobuf:"bytes,1,rep,name=dids,proto3" json:"dids,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDIDsResponse) Reset() {
	*x = ListDIDsResponse{}
	mi := &file_DID_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDIDsResponse) ProtoMessage() {}

func (x *ListDIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DID_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDIDsResponse.ProtoReflect.Descriptor instead.
func (*ListDIDsResponse) Descriptor() ([]byte, []int) {
	return file_DID_proto_rawDescGZIP(), []int{6}
}

func (x *ListDIDsResponse) GetDids() []*DIDInfo {
	if x != nil {
		return x.Dids
	}
	return nil
}

func (x *ListDIDsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type DIDStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalDids     int32                  `protobuf:"varint,1,opt,name=total_dids,json=totalDids,proto3" json:"total_dids,omitempty"`
	TotalBalance  string                 `protobuf:"bytes,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	LastUpdate    int64                  `protobuf:"varint,3,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DIDStats) Reset() {
	*x = DIDStats{}
	mi := &file_DID_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DIDStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDStats) ProtoMessage() {}

func (x *DIDStats) ProtoReflect() protoreflect.Message {
	mi := &file_DID_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDStats.ProtoReflect.Descriptor instead.
func (*DIDStats) Descriptor() ([]byte, []int) {
	return file_DID_proto_rawDescGZIP(), []int{7}
}

func (x *DIDStats) GetTotalDids() int32 {
	if x != nil {
		return x.TotalDids
	}
	return 0
}

func (x *DIDStats) GetTotalBalance() string {
	if x != nil {
		return x.TotalBalance
	}
	return ""
}

func (x *DIDStats) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

var File_DID_proto protoreflect.FileDescriptor

const file_DID_proto_rawDesc = "" +
	"\n" +
	"\tDID.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\x12RegisterDIDRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"t\n" +
	"\x13RegisterDIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\bdid_info\x18\x03 \x01(\v2\x0e.proto.DIDInfoR\adidInfo\"!\n" +
	"\rGetDIDRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"P\n" +
	"\vDIDResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12)\n" +
	"\bdid_info\x18\x02 \x01(\v2\x0e.proto.DIDInfoR\adidInfo\"\xe7\x01\n" +
	"\aDIDInfo\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\x12\x18\n" +
	"\abalance\x18\x05 \x01(\tR\abalance\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\tR\x05nonce\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\x12!\n" +
	"\faccount_type\x18\b \x01(\tR\vaccountType\"?\n" +
	"\x0fListDIDsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"W\n" +
	"\x10ListDIDsResponse\x12\"\n" +
	"\x04dids\x18\x01 \x03(\v2\x0e.proto.DIDInfoR\x04dids\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"o\n" +
	"\bDIDStats\x12\x1d\n" +
	"\n" +
	"total_dids\x18\x01 \x01(\x05R\ttotalDids\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\tR\ftotalBalance\x12\x1f\n" +
	"\vlast_update\x18\x03 \x01(\x03R\n" +
	"lastUpdate2\xfb\x01\n" +
	"\n" +
	"DIDService\x12D\n" +
	"\vRegisterDID\x12\x19.proto.RegisterDIDRequest\x1a\x1a.proto.RegisterDIDResponse\x122\n" +
	"\x06GetDID\x12\x14.proto.GetDIDRequest\x1a\x12.proto.DIDResponse\x12;\n" +
	"\bListDIDs\x12\x16.proto.ListDIDsRequest\x1a\x17.proto.ListDIDsResponse\x126\n" +
	"\vGetDIDStats\x12\x16.google.protobuf.Empty\x1a\x0f.proto.DIDStatsB\x16Z\x14gossipnode/DID/protob\x06proto3"

var (
	file_DID_proto_rawDescOnce sync.Once
	file_DID_proto_rawDescData []byte
)

func file_DID_proto_rawDescGZIP() []byte {
	file_DID_proto_rawDescOnce.Do(func() {
		file_DID_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DID_proto_rawDesc), len(file_DID_proto_rawDesc)))
	})
	return file_DID_proto_rawDescData
}

var file_DID_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_DID_proto_goTypes = []any{
	(*RegisterDIDRequest)(nil),  // 0: proto.RegisterDIDRequest
	(*RegisterDIDResponse)(nil), // 1: proto.RegisterDIDResponse
	(*GetDIDRequest)(nil),       // 2: proto.GetDIDRequest
	(*DIDResponse)(nil),         // 3: proto.DIDResponse
	(*DIDInfo)(nil),             // 4: proto.DIDInfo
	(*ListDIDsRequest)(nil),     // 5: proto.ListDIDsRequest
	(*ListDIDsResponse)(nil),    // 6: proto.ListDIDsResponse
	(*DIDStats)(nil),            // 7: proto.DIDStats
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_DID_proto_depIdxs = []int32{
	4, // 0: proto.RegisterDIDResponse.did_info:type_name -> proto.DIDInfo
	4, // 1: proto.DIDResponse.did_info:type_name -> proto.DIDInfo
	4, // 2: proto.ListDIDsResponse.dids:type_name -> proto.DIDInfo
	0, // 3: proto.DIDService.RegisterDID:input_type -> proto.RegisterDIDRequest
	2, // 4: proto.DIDService.GetDID:input_type -> proto.GetDIDRequest
	5, // 5: proto.DIDService.ListDIDs:input_type -> proto.ListDIDsRequest
	8, // 6: proto.DIDService.GetDIDStats:input_type -> google.protobuf.Empty
	1, // 7: proto.DIDService.RegisterDID:output_type -> proto.RegisterDIDResponse
	3, // 8: proto.DIDService.GetDID:output_type -> proto.DIDResponse
	6, // 9: proto.DIDService.ListDIDs:output_type -> proto.ListDIDsResponse
	7, // 10: proto.DIDService.GetDIDStats:output_type -> proto.DIDStats
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_DID_proto_init() }
func file_DID_proto_init() {
	if File_DID_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DID_proto_rawDesc), len(file_DID_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_DID_proto_goTypes,
		DependencyIndexes: file_DID_proto_depIdxs,
		MessageInfos:      file_DID_proto_msgTypes,
	}.Build()
	File_DID_proto = out.File
	file_DID_proto_goTypes = nil
	file_DID_proto_depIdxs = nil
}
