// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: DID/proto/DID.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DIDService_RegisterDID_FullMethodName = "/proto.DIDService/RegisterDID"
	DIDService_GetDID_FullMethodName      = "/proto.DIDService/GetDID"
	DIDService_ListDIDs_FullMethodName    = "/proto.DIDService/ListDIDs"
	DIDService_GetDIDStats_FullMethodName = "/proto.DIDService/GetDIDStats"
)

// DIDServiceClient is the client API for DIDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DIDServiceClient interface {
	// Register a new DID
	RegisterDID(ctx context.Context, in *RegisterDIDRequest, opts ...grpc.CallOption) (*RegisterDIDResponse, error)
	// Get information about a specific DID
	GetDID(ctx context.Context, in *GetDIDRequest, opts ...grpc.CallOption) (*DIDResponse, error)
	// List all DIDs with pagination
	ListDIDs(ctx context.Context, in *ListDIDsRequest, opts ...grpc.CallOption) (*ListDIDsResponse, error)
	// Get stats about the DID system
	GetDIDStats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DIDStats, error)
}

type dIDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDIDServiceClient(cc grpc.ClientConnInterface) DIDServiceClient {
	return &dIDServiceClient{cc}
}

func (c *dIDServiceClient) RegisterDID(ctx context.Context, in *RegisterDIDRequest, opts ...grpc.CallOption) (*RegisterDIDResponse, error) {
	out := new(RegisterDIDResponse)
	err := c.cc.Invoke(ctx, DIDService_RegisterDID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dIDServiceClient) GetDID(ctx context.Context, in *GetDIDRequest, opts ...grpc.CallOption) (*DIDResponse, error) {
	out := new(DIDResponse)
	err := c.cc.Invoke(ctx, DIDService_GetDID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dIDServiceClient) ListDIDs(ctx context.Context, in *ListDIDsRequest, opts ...grpc.CallOption) (*ListDIDsResponse, error) {
	out := new(ListDIDsResponse)
	err := c.cc.Invoke(ctx, DIDService_ListDIDs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dIDServiceClient) GetDIDStats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DIDStats, error) {
	out := new(DIDStats)
	err := c.cc.Invoke(ctx, DIDService_GetDIDStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DIDServiceServer is the server API for DIDService service.
// All implementations must embed UnimplementedDIDServiceServer
// for forward compatibility
type DIDServiceServer interface {
	// Register a new DID
	RegisterDID(context.Context, *RegisterDIDRequest) (*RegisterDIDResponse, error)
	// Get information about a specific DID
	GetDID(context.Context, *GetDIDRequest) (*DIDResponse, error)
	// List all DIDs with pagination
	ListDIDs(context.Context, *ListDIDsRequest) (*ListDIDsResponse, error)
	// Get stats about the DID system
	GetDIDStats(context.Context, *empty.Empty) (*DIDStats, error)
	mustEmbedUnimplementedDIDServiceServer()
}

// UnimplementedDIDServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDIDServiceServer struct {
}

func (UnimplementedDIDServiceServer) RegisterDID(context.Context, *RegisterDIDRequest) (*RegisterDIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDID not implemented")
}
func (UnimplementedDIDServiceServer) GetDID(context.Context, *GetDIDRequest) (*DIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDID not implemented")
}
func (UnimplementedDIDServiceServer) ListDIDs(context.Context, *ListDIDsRequest) (*ListDIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDIDs not implemented")
}
func (UnimplementedDIDServiceServer) GetDIDStats(context.Context, *empty.Empty) (*DIDStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDIDStats not implemented")
}
func (UnimplementedDIDServiceServer) mustEmbedUnimplementedDIDServiceServer() {}

// UnsafeDIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DIDServiceServer will
// result in compilation errors.
type UnsafeDIDServiceServer interface {
	mustEmbedUnimplementedDIDServiceServer()
}

func RegisterDIDServiceServer(s grpc.ServiceRegistrar, srv DIDServiceServer) {
	s.RegisterService(&DIDService_ServiceDesc, srv)
}

func _DIDService_RegisterDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).RegisterDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_RegisterDID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).RegisterDID(ctx, req.(*RegisterDIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DIDService_GetDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).GetDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_GetDID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).GetDID(ctx, req.(*GetDIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DIDService_ListDIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).ListDIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_ListDIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).ListDIDs(ctx, req.(*ListDIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DIDService_GetDIDStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DIDServiceServer).GetDIDStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DIDService_GetDIDStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DIDServiceServer).GetDIDStats(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DIDService_ServiceDesc is the grpc.ServiceDesc for DIDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DIDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DIDService",
	HandlerType: (*DIDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDID",
			Handler:    _DIDService_RegisterDID_Handler,
		},
		{
			MethodName: "GetDID",
			Handler:    _DIDService_GetDID_Handler,
		},
		{
			MethodName: "ListDIDs",
			Handler:    _DIDService_ListDIDs_Handler,
		},
		{
			MethodName: "GetDIDStats",
			Handler:    _DIDService_GetDIDStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "DID/proto/DID.proto",
}
