// =============================================================================
// FILE: proto/bft/bft.proto
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: bft.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BFTRequest is sent from Sequencer to Buddy nodes
type BFTRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Round          uint64                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`                                         // Round number
	BlockHash      string                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`                 // Block hash to validate
	GossipsubTopic string                 `protobuf:"bytes,3,opt,name=gossipsub_topic,json=gossipsubTopic,proto3" json:"gossipsub_topic,omitempty"`  // GossipSub topic name to join
	AllBuddies     []*BuddyInfo           `protobuf:"bytes,4,rep,name=all_buddies,json=allBuddies,proto3" json:"all_buddies,omitempty"`              // All 13 buddies in this round
	TimeoutSeconds int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // BFT timeout
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BFTRequest) Reset() {
	*x = BFTRequest{}
	mi := &file_bft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BFTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BFTRequest) ProtoMessage() {}

func (x *BFTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BFTRequest.ProtoReflect.Descriptor instead.
func (*BFTRequest) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{0}
}

func (x *BFTRequest) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *BFTRequest) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BFTRequest) GetGossipsubTopic() string {
	if x != nil {
		return x.GossipsubTopic
	}
	return ""
}

func (x *BFTRequest) GetAllBuddies() []*BuddyInfo {
	if x != nil {
		return x.AllBuddies
	}
	return nil
}

func (x *BFTRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// BuddyInfo contains information about each buddy
type BuddyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // Buddy node ID
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                      // Network address
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Ed25519 public key
	Decision      string                 `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`                    // ACCEPT or REJECT (from CRDT phase)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuddyInfo) Reset() {
	*x = BuddyInfo{}
	mi := &file_bft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuddyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuddyInfo) ProtoMessage() {}

func (x *BuddyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuddyInfo.ProtoReflect.Descriptor instead.
func (*BuddyInfo) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{1}
}

func (x *BuddyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuddyInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BuddyInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *BuddyInfo) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

// BFTResponse acknowledges the request
type BFTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`             // Whether buddy accepted the request
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                // Status message
	BuddyId       string                 `protobuf:"bytes,3,opt,name=buddy_id,json=buddyId,proto3" json:"buddy_id,omitempty"` // Responding buddy ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BFTResponse) Reset() {
	*x = BFTResponse{}
	mi := &file_bft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BFTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BFTResponse) ProtoMessage() {}

func (x *BFTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BFTResponse.ProtoReflect.Descriptor instead.
func (*BFTResponse) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{2}
}

func (x *BFTResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BFTResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BFTResponse) GetBuddyId() string {
	if x != nil {
		return x.BuddyId
	}
	return ""
}

// BFTResult is sent from Buddy to Sequencer after consensus
type BFTResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         uint64                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`                                      // Round number
	BlockHash     string                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`              // Block hash
	BuddyId       string                 `protobuf:"bytes,3,opt,name=buddy_id,json=buddyId,proto3" json:"buddy_id,omitempty"`                    // Reporting buddy ID
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`                                  // Whether consensus succeeded
	Decision      string                 `protobuf:"bytes,5,opt,name=decision,proto3" json:"decision,omitempty"`                                 // ACCEPT or REJECT
	BlockAccepted bool                   `protobuf:"varint,6,opt,name=block_accepted,json=blockAccepted,proto3" json:"block_accepted,omitempty"` // Final decision
	PrepareCount  int32                  `protobuf:"varint,7,opt,name=prepare_count,json=prepareCount,proto3" json:"prepare_count,omitempty"`    // Number of PREPARE votes
	CommitCount   int32                  `protobuf:"varint,8,opt,name=commit_count,json=commitCount,proto3" json:"commit_count,omitempty"`       // Number of COMMIT votes
	Byzantine     []string               `protobuf:"bytes,9,rep,name=byzantine,proto3" json:"byzantine,omitempty"`                               // Byzantine nodes detected
	DurationMs    int64                  `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`         // Total duration in milliseconds
	FailureReason string                 `protobuf:"bytes,11,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"` // Reason if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BFTResult) Reset() {
	*x = BFTResult{}
	mi := &file_bft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BFTResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BFTResult) ProtoMessage() {}

func (x *BFTResult) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BFTResult.ProtoReflect.Descriptor instead.
func (*BFTResult) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{3}
}

func (x *BFTResult) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *BFTResult) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BFTResult) GetBuddyId() string {
	if x != nil {
		return x.BuddyId
	}
	return ""
}

func (x *BFTResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BFTResult) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *BFTResult) GetBlockAccepted() bool {
	if x != nil {
		return x.BlockAccepted
	}
	return false
}

func (x *BFTResult) GetPrepareCount() int32 {
	if x != nil {
		return x.PrepareCount
	}
	return 0
}

func (x *BFTResult) GetCommitCount() int32 {
	if x != nil {
		return x.CommitCount
	}
	return 0
}

func (x *BFTResult) GetByzantine() []string {
	if x != nil {
		return x.Byzantine
	}
	return nil
}

func (x *BFTResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *BFTResult) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

// ResultAck acknowledges result receipt
type ResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultAck) Reset() {
	*x = ResultAck{}
	mi := &file_bft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAck) ProtoMessage() {}

func (x *ResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAck.ProtoReflect.Descriptor instead.
func (*ResultAck) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{4}
}

func (x *ResultAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *ResultAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bft_proto protoreflect.FileDescriptor

const file_bft_proto_rawDesc = "" +
	"\n" +
	"\tbft.proto\x12\x03bft\"\xc4\x01\n" +
	"\n" +
	"BFTRequest\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\tR\tblockHash\x12'\n" +
	"\x0fgossipsub_topic\x18\x03 \x01(\tR\x0egossipsubTopic\x12/\n" +
	"\vall_buddies\x18\x04 \x03(\v2\x0e.bft.BuddyInfoR\n" +
	"allBuddies\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\"p\n" +
	"\tBuddyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x1a\n" +
	"\bdecision\x18\x04 \x01(\tR\bdecision\"^\n" +
	"\vBFTResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bbuddy_id\x18\x03 \x01(\tR\abuddyId\"\xe6\x02\n" +
	"\tBFTResult\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\tR\tblockHash\x12\x19\n" +
	"\bbuddy_id\x18\x03 \x01(\tR\abuddyId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1a\n" +
	"\bdecision\x18\x05 \x01(\tR\bdecision\x12%\n" +
	"\x0eblock_accepted\x18\x06 \x01(\bR\rblockAccepted\x12#\n" +
	"\rprepare_count\x18\a \x01(\x05R\fprepareCount\x12!\n" +
	"\fcommit_count\x18\b \x01(\x05R\vcommitCount\x12\x1c\n" +
	"\tbyzantine\x18\t \x03(\tR\tbyzantine\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x03R\n" +
	"durationMs\x12%\n" +
	"\x0efailure_reason\x18\v \x01(\tR\rfailureReason\"A\n" +
	"\tResultAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2n\n" +
	"\n" +
	"BFTService\x120\n" +
	"\vInitiateBFT\x12\x0f.bft.BFTRequest\x1a\x10.bft.BFTResponse\x12.\n" +
	"\fReportResult\x12\x0e.bft.BFTResult\x1a\x0e.bft.ResultAckBIZGgithub.com/JupiterMetaLabs/Asynchronous-Validation-Consensus/pkg/bft/pbb\x06proto3"

var (
	file_bft_proto_rawDescOnce sync.Once
	file_bft_proto_rawDescData []byte
)

func file_bft_proto_rawDescGZIP() []byte {
	file_bft_proto_rawDescOnce.Do(func() {
		file_bft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bft_proto_rawDesc), len(file_bft_proto_rawDesc)))
	})
	return file_bft_proto_rawDescData
}

var file_bft_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bft_proto_goTypes = []any{
	(*BFTRequest)(nil),  // 0: bft.BFTRequest
	(*BuddyInfo)(nil),   // 1: bft.BuddyInfo
	(*BFTResponse)(nil), // 2: bft.BFTResponse
	(*BFTResult)(nil),   // 3: bft.BFTResult
	(*ResultAck)(nil),   // 4: bft.ResultAck
}
var file_bft_proto_depIdxs = []int32{
	1, // 0: bft.BFTRequest.all_buddies:type_name -> bft.BuddyInfo
	0, // 1: bft.BFTService.InitiateBFT:input_type -> bft.BFTRequest
	3, // 2: bft.BFTService.ReportResult:input_type -> bft.BFTResult
	2, // 3: bft.BFTService.InitiateBFT:output_type -> bft.BFTResponse
	4, // 4: bft.BFTService.ReportResult:output_type -> bft.ResultAck
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bft_proto_init() }
func file_bft_proto_init() {
	if File_bft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bft_proto_rawDesc), len(file_bft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bft_proto_goTypes,
		DependencyIndexes: file_bft_proto_depIdxs,
		MessageInfos:      file_bft_proto_msgTypes,
	}.Build()
	File_bft_proto = out.File
	file_bft_proto_goTypes = nil
	file_bft_proto_depIdxs = nil
}
