// =============================================================================
// FILE: proto/bft/bft.proto
// =============================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: bft.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BFTService_InitiateBFT_FullMethodName  = "/bft.BFTService/InitiateBFT"
	BFTService_ReportResult_FullMethodName = "/bft.BFTService/ReportResult"
)

// BFTServiceClient is the client API for BFTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BFTService handles BFT consensus coordination
type BFTServiceClient interface {
	// Sequencer calls this to initiate BFT on buddy nodes
	InitiateBFT(ctx context.Context, in *BFTRequest, opts ...grpc.CallOption) (*BFTResponse, error)
	// Buddy calls this to report result back to Sequencer
	ReportResult(ctx context.Context, in *BFTResult, opts ...grpc.CallOption) (*ResultAck, error)
}

type bFTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBFTServiceClient(cc grpc.ClientConnInterface) BFTServiceClient {
	return &bFTServiceClient{cc}
}

func (c *bFTServiceClient) InitiateBFT(ctx context.Context, in *BFTRequest, opts ...grpc.CallOption) (*BFTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BFTResponse)
	err := c.cc.Invoke(ctx, BFTService_InitiateBFT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFTServiceClient) ReportResult(ctx context.Context, in *BFTResult, opts ...grpc.CallOption) (*ResultAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultAck)
	err := c.cc.Invoke(ctx, BFTService_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BFTServiceServer is the server API for BFTService service.
// All implementations must embed UnimplementedBFTServiceServer
// for forward compatibility.
//
// BFTService handles BFT consensus coordination
type BFTServiceServer interface {
	// Sequencer calls this to initiate BFT on buddy nodes
	InitiateBFT(context.Context, *BFTRequest) (*BFTResponse, error)
	// Buddy calls this to report result back to Sequencer
	ReportResult(context.Context, *BFTResult) (*ResultAck, error)
	mustEmbedUnimplementedBFTServiceServer()
}

// UnimplementedBFTServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBFTServiceServer struct{}

func (UnimplementedBFTServiceServer) InitiateBFT(context.Context, *BFTRequest) (*BFTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateBFT not implemented")
}
func (UnimplementedBFTServiceServer) ReportResult(context.Context, *BFTResult) (*ResultAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedBFTServiceServer) mustEmbedUnimplementedBFTServiceServer() {}
func (UnimplementedBFTServiceServer) testEmbeddedByValue()                    {}

// UnsafeBFTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BFTServiceServer will
// result in compilation errors.
type UnsafeBFTServiceServer interface {
	mustEmbedUnimplementedBFTServiceServer()
}

func RegisterBFTServiceServer(s grpc.ServiceRegistrar, srv BFTServiceServer) {
	// If the following call pancis, it indicates UnimplementedBFTServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BFTService_ServiceDesc, srv)
}

func _BFTService_InitiateBFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BFTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFTServiceServer).InitiateBFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFTService_InitiateBFT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFTServiceServer).InitiateBFT(ctx, req.(*BFTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFTService_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BFTResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFTServiceServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFTService_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFTServiceServer).ReportResult(ctx, req.(*BFTResult))
	}
	return interceptor(ctx, in, info, handler)
}

// BFTService_ServiceDesc is the grpc.ServiceDesc for BFTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BFTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bft.BFTService",
	HandlerType: (*BFTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateBFT",
			Handler:    _BFTService_InitiateBFT_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _BFTService_ReportResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bft.proto",
}
