// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: block.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ZKBlock message represents a block processed by the ZKVM
type ZKBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ZK-Stark proof data
	StarkProof []byte   `protobuf:"bytes,1,opt,name=stark_proof,json=starkProof,proto3" json:"stark_proof,omitempty"`
	Commitment []uint32 `protobuf:"varint,2,rep,packed,name=commitment,proto3" json:"commitment,omitempty"`
	ProofHash  string   `protobuf:"bytes,3,opt,name=proof_hash,json=proofHash,proto3" json:"proof_hash,omitempty"`
	Status     string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TxnsRoot   string   `protobuf:"bytes,5,opt,name=txns_root,json=txnsRoot,proto3" json:"txns_root,omitempty"`
	// Block data
	Transactions  []*Transaction `protobuf:"bytes,6,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Timestamp     int64          `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData     string         `protobuf:"bytes,8,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	StateRoot     []byte         `protobuf:"bytes,9,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	LogsBloom     []byte         `protobuf:"bytes,10,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	CoinbaseAddr  []byte         `protobuf:"bytes,11,opt,name=coinbase_addr,json=coinbaseAddr,proto3" json:"coinbase_addr,omitempty"`
	ZkvmAddr      []byte         `protobuf:"bytes,12,opt,name=zkvm_addr,json=zkvmAddr,proto3" json:"zkvm_addr,omitempty"`
	PrevHash      []byte         `protobuf:"bytes,13,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	BlockHash     []byte         `protobuf:"bytes,14,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	GasLimit      uint64         `protobuf:"varint,15,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed       uint64         `protobuf:"varint,16,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	BlockNumber   uint64         `protobuf:"varint,17,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZKBlock) Reset() {
	*x = ZKBlock{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZKBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKBlock) ProtoMessage() {}

func (x *ZKBlock) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKBlock.ProtoReflect.Descriptor instead.
func (*ZKBlock) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *ZKBlock) GetStarkProof() []byte {
	if x != nil {
		return x.StarkProof
	}
	return nil
}

func (x *ZKBlock) GetCommitment() []uint32 {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *ZKBlock) GetProofHash() string {
	if x != nil {
		return x.ProofHash
	}
	return ""
}

func (x *ZKBlock) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ZKBlock) GetTxnsRoot() string {
	if x != nil {
		return x.TxnsRoot
	}
	return ""
}

func (x *ZKBlock) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ZKBlock) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ZKBlock) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *ZKBlock) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ZKBlock) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ZKBlock) GetCoinbaseAddr() []byte {
	if x != nil {
		return x.CoinbaseAddr
	}
	return nil
}

func (x *ZKBlock) GetZkvmAddr() []byte {
	if x != nil {
		return x.ZkvmAddr
	}
	return nil
}

func (x *ZKBlock) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *ZKBlock) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ZKBlock) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ZKBlock) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ZKBlock) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

// Transaction message
type Transaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hash           []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From           []byte                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To             []byte                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value          []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Type           uint32                 `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp      uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId        []byte                 `protobuf:"bytes,7,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce          uint64                 `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasLimit       uint64                 `protobuf:"varint,9,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice       []byte                 `protobuf:"bytes,10,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	MaxFee         []byte                 `protobuf:"bytes,11,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"`
	MaxPriorityFee []byte                 `protobuf:"bytes,12,opt,name=max_priority_fee,json=maxPriorityFee,proto3" json:"max_priority_fee,omitempty"`
	Data           []byte                 `protobuf:"bytes,13,opt,name=data,proto3" json:"data,omitempty"`
	AccessList     *AccessList            `protobuf:"bytes,14,opt,name=access_list,json=accessList,proto3" json:"access_list,omitempty"`
	V              []byte                 `protobuf:"bytes,15,opt,name=v,proto3" json:"v,omitempty"`
	R              []byte                 `protobuf:"bytes,16,opt,name=r,proto3" json:"r,omitempty"`
	S              []byte                 `protobuf:"bytes,17,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Transaction) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Transaction) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Transaction) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Transaction) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Transaction) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *Transaction) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *Transaction) GetMaxFee() []byte {
	if x != nil {
		return x.MaxFee
	}
	return nil
}

func (x *Transaction) GetMaxPriorityFee() []byte {
	if x != nil {
		return x.MaxPriorityFee
	}
	return nil
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction) GetAccessList() *AccessList {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *Transaction) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *Transaction) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *Transaction) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

// AccessList message
type AccessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessTuples  []*AccessTuple         `protobuf:"bytes,1,rep,name=access_tuples,json=accessTuples,proto3" json:"access_tuples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessList) Reset() {
	*x = AccessList{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessList) ProtoMessage() {}

func (x *AccessList) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessList.ProtoReflect.Descriptor instead.
func (*AccessList) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *AccessList) GetAccessTuples() []*AccessTuple {
	if x != nil {
		return x.AccessTuples
	}
	return nil
}

type AccessTuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	StorageKeys   [][]byte               `protobuf:"bytes,2,rep,name=storage_keys,json=storageKeys,proto3" json:"storage_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTuple) Reset() {
	*x = AccessTuple{}
	mi := &file_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTuple) ProtoMessage() {}

func (x *AccessTuple) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTuple.ProtoReflect.Descriptor instead.
func (*AccessTuple) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{3}
}

func (x *AccessTuple) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AccessTuple) GetStorageKeys() [][]byte {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

// ProcessBlock request and response
type ProcessBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *ZKBlock               `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessBlockRequest) Reset() {
	*x = ProcessBlockRequest{}
	mi := &file_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessBlockRequest) ProtoMessage() {}

func (x *ProcessBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessBlockRequest.ProtoReflect.Descriptor instead.
func (*ProcessBlockRequest) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessBlockRequest) GetBlock() *ZKBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

type ProcessBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BlockHash     string                 `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessBlockResponse) Reset() {
	*x = ProcessBlockResponse{}
	mi := &file_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessBlockResponse) ProtoMessage() {}

func (x *ProcessBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessBlockResponse.ProtoReflect.Descriptor instead.
func (*ProcessBlockResponse) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessBlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessBlockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessBlockResponse) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *ProcessBlockResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ProcessBlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\x05Block\"\xaa\x04\n" +
	"\aZKBlock\x12\x1f\n" +
	"\vstark_proof\x18\x01 \x01(\fR\n" +
	"starkProof\x12\x1e\n" +
	"\n" +
	"commitment\x18\x02 \x03(\rR\n" +
	"commitment\x12\x1d\n" +
	"\n" +
	"proof_hash\x18\x03 \x01(\tR\tproofHash\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\ttxns_root\x18\x05 \x01(\tR\btxnsRoot\x126\n" +
	"\ftransactions\x18\x06 \x03(\v2\x12.Block.TransactionR\ftransactions\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"extra_data\x18\b \x01(\tR\textraData\x12\x1d\n" +
	"\n" +
	"state_root\x18\t \x01(\fR\tstateRoot\x12\x1d\n" +
	"\n" +
	"logs_bloom\x18\n" +
	" \x01(\fR\tlogsBloom\x12#\n" +
	"\rcoinbase_addr\x18\v \x01(\fR\fcoinbaseAddr\x12\x1b\n" +
	"\tzkvm_addr\x18\f \x01(\fR\bzkvmAddr\x12\x1b\n" +
	"\tprev_hash\x18\r \x01(\fR\bprevHash\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x0e \x01(\fR\tblockHash\x12\x1b\n" +
	"\tgas_limit\x18\x0f \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\x10 \x01(\x04R\agasUsed\x12!\n" +
	"\fblock_number\x18\x11 \x01(\x04R\vblockNumber\"\xad\x03\n" +
	"\vTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04from\x18\x02 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x12\n" +
	"\x04type\x18\x05 \x01(\rR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x19\n" +
	"\bchain_id\x18\a \x01(\fR\achainId\x12\x14\n" +
	"\x05nonce\x18\b \x01(\x04R\x05nonce\x12\x1b\n" +
	"\tgas_limit\x18\t \x01(\x04R\bgasLimit\x12\x1b\n" +
	"\tgas_price\x18\n" +
	" \x01(\fR\bgasPrice\x12\x17\n" +
	"\amax_fee\x18\v \x01(\fR\x06maxFee\x12(\n" +
	"\x10max_priority_fee\x18\f \x01(\fR\x0emaxPriorityFee\x12\x12\n" +
	"\x04data\x18\r \x01(\fR\x04data\x122\n" +
	"\vaccess_list\x18\x0e \x01(\v2\x11.Block.AccessListR\n" +
	"accessList\x12\f\n" +
	"\x01v\x18\x0f \x01(\fR\x01v\x12\f\n" +
	"\x01r\x18\x10 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x11 \x01(\fR\x01s\"E\n" +
	"\n" +
	"AccessList\x127\n" +
	"\raccess_tuples\x18\x01 \x03(\v2\x12.Block.AccessTupleR\faccessTuples\"J\n" +
	"\vAccessTuple\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12!\n" +
	"\fstorage_keys\x18\x02 \x03(\fR\vstorageKeys\";\n" +
	"\x13ProcessBlockRequest\x12$\n" +
	"\x05block\x18\x01 \x01(\v2\x0e.Block.ZKBlockR\x05block\"\xa2\x01\n" +
	"\x14ProcessBlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\tR\tblockHash\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x04R\vblockNumber\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2W\n" +
	"\fBlockService\x12G\n" +
	"\fProcessBlock\x12\x1a.Block.ProcessBlockRequest\x1a\x1b.Block.ProcessBlockResponseB\x18Z\x16gossipnode/Block/protob\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_block_proto_goTypes = []any{
	(*ZKBlock)(nil),              // 0: Block.ZKBlock
	(*Transaction)(nil),          // 1: Block.Transaction
	(*AccessList)(nil),           // 2: Block.AccessList
	(*AccessTuple)(nil),          // 3: Block.AccessTuple
	(*ProcessBlockRequest)(nil),  // 4: Block.ProcessBlockRequest
	(*ProcessBlockResponse)(nil), // 5: Block.ProcessBlockResponse
}
var file_block_proto_depIdxs = []int32{
	1, // 0: Block.ZKBlock.transactions:type_name -> Block.Transaction
	2, // 1: Block.Transaction.access_list:type_name -> Block.AccessList
	3, // 2: Block.AccessList.access_tuples:type_name -> Block.AccessTuple
	0, // 3: Block.ProcessBlockRequest.block:type_name -> Block.ZKBlock
	4, // 4: Block.BlockService.ProcessBlock:input_type -> Block.ProcessBlockRequest
	5, // 5: Block.BlockService.ProcessBlock:output_type -> Block.ProcessBlockResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
