// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: explorer.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common pagination request
type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_explorer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Block requests and responses
type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Block hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_explorer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{1}
}

func (x *BlockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BlockNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"` // Block number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockNumberRequest) Reset() {
	*x = BlockNumberRequest{}
	mi := &file_explorer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockNumberRequest) ProtoMessage() {}

func (x *BlockNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockNumberRequest.ProtoReflect.Descriptor instead.
func (*BlockNumberRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{2}
}

func (x *BlockNumberRequest) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type BlockCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // Number of blocks to return (max 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCountRequest) Reset() {
	*x = BlockCountRequest{}
	mi := &file_explorer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCountRequest) ProtoMessage() {}

func (x *BlockCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCountRequest.ProtoReflect.Descriptor instead.
func (*BlockCountRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{3}
}

func (x *BlockCountRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BlockPagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"` // e.g., "number", "timestamp"
	Desc          bool                   `protobuf:"varint,4,opt,name=desc,proto3" json:"desc,omitempty"`                     // Sort in descending order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPagination) Reset() {
	*x = BlockPagination{}
	mi := &file_explorer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPagination) ProtoMessage() {}

func (x *BlockPagination) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPagination.ProtoReflect.Descriptor instead.
func (*BlockPagination) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{4}
}

func (x *BlockPagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BlockPagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BlockPagination) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *BlockPagination) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     string                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	StarkProof    []byte                 `protobuf:"bytes,2,opt,name=stark_proof,json=starkProof,proto3" json:"stark_proof,omitempty"`
	Commitment    []uint32               `protobuf:"varint,3,rep,packed,name=commitment,proto3" json:"commitment,omitempty"`
	ProofHash     string                 `protobuf:"bytes,4,opt,name=proof_hash,json=proofHash,proto3" json:"proof_hash,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TxnsRoot      string                 `protobuf:"bytes,6,opt,name=txns_root,json=txnsRoot,proto3" json:"txns_root,omitempty"`
	Transactions  []*ZKBlockTransaction  `protobuf:"bytes,7,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData     []byte                 `protobuf:"bytes,9,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,10,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	LogsBloom     []byte                 `protobuf:"bytes,11,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	CoinbaseAddr  string                 `protobuf:"bytes,12,opt,name=coinbase_addr,json=coinbaseAddr,proto3" json:"coinbase_addr,omitempty"`
	ZkvmAddr      string                 `protobuf:"bytes,13,opt,name=zkvm_addr,json=zkvmAddr,proto3" json:"zkvm_addr,omitempty"`
	PrevHash      []byte                 `protobuf:"bytes,14,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,15,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,16,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,17,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_explorer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{5}
}

func (x *BlockResponse) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BlockResponse) GetStarkProof() []byte {
	if x != nil {
		return x.StarkProof
	}
	return nil
}

func (x *BlockResponse) GetCommitment() []uint32 {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *BlockResponse) GetProofHash() string {
	if x != nil {
		return x.ProofHash
	}
	return ""
}

func (x *BlockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BlockResponse) GetTxnsRoot() string {
	if x != nil {
		return x.TxnsRoot
	}
	return ""
}

func (x *BlockResponse) GetTransactions() []*ZKBlockTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BlockResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockResponse) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *BlockResponse) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockResponse) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *BlockResponse) GetCoinbaseAddr() string {
	if x != nil {
		return x.CoinbaseAddr
	}
	return ""
}

func (x *BlockResponse) GetZkvmAddr() string {
	if x != nil {
		return x.ZkvmAddr
	}
	return ""
}

func (x *BlockResponse) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *BlockResponse) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *BlockResponse) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *BlockResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type BlockListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockResponse       `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockListResponse) Reset() {
	*x = BlockListResponse{}
	mi := &file_explorer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockListResponse) ProtoMessage() {}

func (x *BlockListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockListResponse.ProtoReflect.Descriptor instead.
func (*BlockListResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{6}
}

func (x *BlockListResponse) GetBlocks() []*BlockResponse {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *BlockListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BlockListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BlockListResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Transaction requests and responses
type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // Transaction hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_explorer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type TransactionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hash             string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From             string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To               string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value            string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Type             string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp        string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId          string                 `protobuf:"bytes,7,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce            string                 `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasLimit         string                 `protobuf:"bytes,9,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	MaxFee           string                 `protobuf:"bytes,10,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"`
	MaxPriorityFee   string                 `protobuf:"bytes,11,opt,name=max_priority_fee,json=maxPriorityFee,proto3" json:"max_priority_fee,omitempty"`
	Data             string                 `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
	BlockHash        string                 `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNumber      uint64                 `protobuf:"varint,14,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TransactionIndex uint32                 `protobuf:"varint,15,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_explorer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TransactionResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransactionResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransactionResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TransactionResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransactionResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TransactionResponse) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *TransactionResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *TransactionResponse) GetGasLimit() string {
	if x != nil {
		return x.GasLimit
	}
	return ""
}

func (x *TransactionResponse) GetMaxFee() string {
	if x != nil {
		return x.MaxFee
	}
	return ""
}

func (x *TransactionResponse) GetMaxPriorityFee() string {
	if x != nil {
		return x.MaxPriorityFee
	}
	return ""
}

func (x *TransactionResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TransactionResponse) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *TransactionResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *TransactionResponse) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

type TransactionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionResponse `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionListResponse) Reset() {
	*x = TransactionListResponse{}
	mi := &file_explorer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionListResponse) ProtoMessage() {}

func (x *TransactionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionListResponse.ProtoReflect.Descriptor instead.
func (*TransactionListResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionListResponse) GetTransactions() []*TransactionResponse {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *TransactionListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TransactionListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TransactionListResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// DID requests and responses
type DIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DIDRequest) Reset() {
	*x = DIDRequest{}
	mi := &file_explorer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDRequest) ProtoMessage() {}

func (x *DIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDRequest.ProtoReflect.Descriptor instead.
func (*DIDRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{10}
}

func (x *DIDRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type DIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Balance       string                 `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce         uint64                 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DIDResponse) Reset() {
	*x = DIDResponse{}
	mi := &file_explorer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDResponse) ProtoMessage() {}

func (x *DIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDResponse.ProtoReflect.Descriptor instead.
func (*DIDResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{11}
}

func (x *DIDResponse) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *DIDResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DIDResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *DIDResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *DIDResponse) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *DIDResponse) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DIDResponse) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DIDListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dids          []*DIDResponse         `protobuf:"bytes,1,rep,name=dids,proto3" json:"dids,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DIDListResponse) Reset() {
	*x = DIDListResponse{}
	mi := &file_explorer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DIDListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDListResponse) ProtoMessage() {}

func (x *DIDListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDListResponse.ProtoReflect.Descriptor instead.
func (*DIDListResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{12}
}

func (x *DIDListResponse) GetDids() []*DIDResponse {
	if x != nil {
		return x.Dids
	}
	return nil
}

func (x *DIDListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DIDListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DIDListResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Stats response
type StatsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LatestBlockNumber      uint64                 `protobuf:"varint,1,opt,name=latest_block_number,json=latestBlockNumber,proto3" json:"latest_block_number,omitempty"`
	TotalBlocks            uint64                 `protobuf:"varint,2,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"`
	TotalTransactions      uint64                 `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalDids              uint64                 `protobuf:"varint,4,opt,name=total_dids,json=totalDids,proto3" json:"total_dids,omitempty"`
	PendingTransactions    uint64                 `protobuf:"varint,5,opt,name=pending_transactions,json=pendingTransactions,proto3" json:"pending_transactions,omitempty"`
	TotalValueTransferred  string                 `protobuf:"bytes,6,opt,name=total_value_transferred,json=totalValueTransferred,proto3" json:"total_value_transferred,omitempty"`
	AverageBlockTime       float64                `protobuf:"fixed64,7,opt,name=average_block_time,json=averageBlockTime,proto3" json:"average_block_time,omitempty"` // in seconds
	TransactionCountByType map[string]uint64      `protobuf:"bytes,8,rep,name=transaction_count_by_type,json=transactionCountByType,proto3" json:"transaction_count_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LastUpdated            *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_explorer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{13}
}

func (x *StatsResponse) GetLatestBlockNumber() uint64 {
	if x != nil {
		return x.LatestBlockNumber
	}
	return 0
}

func (x *StatsResponse) GetTotalBlocks() uint64 {
	if x != nil {
		return x.TotalBlocks
	}
	return 0
}

func (x *StatsResponse) GetTotalTransactions() uint64 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *StatsResponse) GetTotalDids() uint64 {
	if x != nil {
		return x.TotalDids
	}
	return 0
}

func (x *StatsResponse) GetPendingTransactions() uint64 {
	if x != nil {
		return x.PendingTransactions
	}
	return 0
}

func (x *StatsResponse) GetTotalValueTransferred() string {
	if x != nil {
		return x.TotalValueTransferred
	}
	return ""
}

func (x *StatsResponse) GetAverageBlockTime() float64 {
	if x != nil {
		return x.AverageBlockTime
	}
	return 0
}

func (x *StatsResponse) GetTransactionCountByType() map[string]uint64 {
	if x != nil {
		return x.TransactionCountByType
	}
	return nil
}

func (x *StatsResponse) GetLastUpdated() *timestamp.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// ZKBlockTransaction represents a transaction in a ZK block
type ZKBlockTransaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hash           string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From           string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To             string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value          string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp      string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId        string                 `protobuf:"bytes,7,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce          string                 `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasLimit       string                 `protobuf:"bytes,9,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	MaxFee         string                 `protobuf:"bytes,10,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"`
	MaxPriorityFee string                 `protobuf:"bytes,11,opt,name=max_priority_fee,json=maxPriorityFee,proto3" json:"max_priority_fee,omitempty"`
	Data           string                 `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ZKBlockTransaction) Reset() {
	*x = ZKBlockTransaction{}
	mi := &file_explorer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZKBlockTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKBlockTransaction) ProtoMessage() {}

func (x *ZKBlockTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKBlockTransaction.ProtoReflect.Descriptor instead.
func (*ZKBlockTransaction) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{14}
}

func (x *ZKBlockTransaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ZKBlockTransaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ZKBlockTransaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ZKBlockTransaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ZKBlockTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ZKBlockTransaction) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ZKBlockTransaction) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ZKBlockTransaction) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ZKBlockTransaction) GetGasLimit() string {
	if x != nil {
		return x.GasLimit
	}
	return ""
}

func (x *ZKBlockTransaction) GetMaxFee() string {
	if x != nil {
		return x.MaxFee
	}
	return ""
}

func (x *ZKBlockTransaction) GetMaxPriorityFee() string {
	if x != nil {
		return x.MaxPriorityFee
	}
	return ""
}

func (x *ZKBlockTransaction) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_explorer_proto protoreflect.FileDescriptor

const file_explorer_proto_rawDesc = "" +
	"\n" +
	"\x0eexplorer.proto\x12\bexplorer\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x1e\n" +
	"\fBlockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x12BlockNumberRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\")\n" +
	"\x11BlockCountRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"j\n" +
	"\x0fBlockPagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\bR\x04desc\"\xba\x04\n" +
	"\rBlockResponse\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\tR\tblockHash\x12\x1f\n" +
	"\vstark_proof\x18\x02 \x01(\fR\n" +
	"starkProof\x12\x1e\n" +
	"\n" +
	"commitment\x18\x03 \x03(\rR\n" +
	"commitment\x12\x1d\n" +
	"\n" +
	"proof_hash\x18\x04 \x01(\tR\tproofHash\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\ttxns_root\x18\x06 \x01(\tR\btxnsRoot\x12@\n" +
	"\ftransactions\x18\a \x03(\v2\x1c.explorer.ZKBlockTransactionR\ftransactions\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"extra_data\x18\t \x01(\fR\textraData\x12\x1d\n" +
	"\n" +
	"state_root\x18\n" +
	" \x01(\fR\tstateRoot\x12\x1d\n" +
	"\n" +
	"logs_bloom\x18\v \x01(\fR\tlogsBloom\x12#\n" +
	"\rcoinbase_addr\x18\f \x01(\tR\fcoinbaseAddr\x12\x1b\n" +
	"\tzkvm_addr\x18\r \x01(\tR\bzkvmAddr\x12\x1b\n" +
	"\tprev_hash\x18\x0e \x01(\fR\bprevHash\x12\x1b\n" +
	"\tgas_limit\x18\x0f \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\x10 \x01(\x04R\agasUsed\x12!\n" +
	"\fblock_number\x18\x11 \x01(\x04R\vblockNumber\"\x84\x01\n" +
	"\x11BlockListResponse\x12/\n" +
	"\x06blocks\x18\x01 \x03(\v2\x17.explorer.BlockResponseR\x06blocks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"(\n" +
	"\x12TransactionRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xa9\x03\n" +
	"\x13TransactionResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\x12\x19\n" +
	"\bchain_id\x18\a \x01(\tR\achainId\x12\x14\n" +
	"\x05nonce\x18\b \x01(\tR\x05nonce\x12\x1b\n" +
	"\tgas_limit\x18\t \x01(\tR\bgasLimit\x12\x17\n" +
	"\amax_fee\x18\n" +
	" \x01(\tR\x06maxFee\x12(\n" +
	"\x10max_priority_fee\x18\v \x01(\tR\x0emaxPriorityFee\x12\x12\n" +
	"\x04data\x18\f \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"block_hash\x18\r \x01(\tR\tblockHash\x12!\n" +
	"\fblock_number\x18\x0e \x01(\x04R\vblockNumber\x12+\n" +
	"\x11transaction_index\x18\x0f \x01(\rR\x10transactionIndex\"\x9c\x01\n" +
	"\x17TransactionListResponse\x12A\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1d.explorer.TransactionResponseR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x1e\n" +
	"\n" +
	"DIDRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"\xea\x02\n" +
	"\vDIDResponse\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\abalance\x18\x03 \x01(\tR\abalance\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\x12E\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2%.explorer.DIDResponse.AttributesEntryR\n" +
	"attributes\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\x0fDIDListResponse\x12)\n" +
	"\x04dids\x18\x01 \x03(\v2\x15.explorer.DIDResponseR\x04dids\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xc3\x04\n" +
	"\rStatsResponse\x12.\n" +
	"\x13latest_block_number\x18\x01 \x01(\x04R\x11latestBlockNumber\x12!\n" +
	"\ftotal_blocks\x18\x02 \x01(\x04R\vtotalBlocks\x12-\n" +
	"\x12total_transactions\x18\x03 \x01(\x04R\x11totalTransactions\x12\x1d\n" +
	"\n" +
	"total_dids\x18\x04 \x01(\x04R\ttotalDids\x121\n" +
	"\x14pending_transactions\x18\x05 \x01(\x04R\x13pendingTransactions\x126\n" +
	"\x17total_value_transferred\x18\x06 \x01(\tR\x15totalValueTransferred\x12,\n" +
	"\x12average_block_time\x18\a \x01(\x01R\x10averageBlockTime\x12n\n" +
	"\x19transaction_count_by_type\x18\b \x03(\v23.explorer.StatsResponse.TransactionCountByTypeEntryR\x16transactionCountByType\x12=\n" +
	"\flast_updated\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1aI\n" +
	"\x1bTransactionCountByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xb9\x02\n" +
	"\x12ZKBlockTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\x12\x19\n" +
	"\bchain_id\x18\a \x01(\tR\achainId\x12\x14\n" +
	"\x05nonce\x18\b \x01(\tR\x05nonce\x12\x1b\n" +
	"\tgas_limit\x18\t \x01(\tR\bgasLimit\x12\x17\n" +
	"\amax_fee\x18\n" +
	" \x01(\tR\x06maxFee\x12(\n" +
	"\x10max_priority_fee\x18\v \x01(\tR\x0emaxPriorityFee\x12\x12\n" +
	"\x04data\x18\f \x01(\tR\x04data2\xbe\x06\n" +
	"\x0fExplorerService\x12=\n" +
	"\bGetBlock\x12\x16.explorer.BlockRequest\x1a\x17.explorer.BlockResponse\"\x00\x12K\n" +
	"\x10GetBlockByNumber\x12\x1c.explorer.BlockNumberRequest\x1a\x17.explorer.BlockResponse\"\x00\x12F\n" +
	"\n" +
	"ListBlocks\x12\x19.explorer.BlockPagination\x1a\x1b.explorer.BlockListResponse\"\x00\x12M\n" +
	"\x0fGetLatestBlocks\x12\x1b.explorer.BlockCountRequest\x1a\x1b.explorer.BlockListResponse\"\x00\x12O\n" +
	"\x10GetMissingBlocks\x12\x1c.explorer.BlockNumberRequest\x1a\x1b.explorer.BlockListResponse\"\x00\x12O\n" +
	"\x0eGetTransaction\x12\x1c.explorer.TransactionRequest\x1a\x1d.explorer.TransactionResponse\"\x00\x12\\\n" +
	"\x17ListTransactionsInBlock\x12\x1c.explorer.BlockNumberRequest\x1a!.explorer.TransactionListResponse\"\x00\x12D\n" +
	"\bListDIDs\x12\x1b.explorer.PaginationRequest\x1a\x19.explorer.DIDListResponse\"\x00\x12>\n" +
	"\rGetDIDDetails\x12\x14.explorer.DIDRequest\x1a\x15.explorer.DIDResponse\"\x00\x12=\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x17.explorer.StatsResponse\"\x00\x12C\n" +
	"\fStreamBlocks\x12\x16.google.protobuf.Empty\x1a\x17.explorer.BlockResponse\"\x000\x01B:Z8github.com/yourusername/P2P-Communication/explorer/protob\x06proto3"

var (
	file_explorer_proto_rawDescOnce sync.Once
	file_explorer_proto_rawDescData []byte
)

func file_explorer_proto_rawDescGZIP() []byte {
	file_explorer_proto_rawDescOnce.Do(func() {
		file_explorer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_explorer_proto_rawDesc), len(file_explorer_proto_rawDesc)))
	})
	return file_explorer_proto_rawDescData
}

var file_explorer_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_explorer_proto_goTypes = []any{
	(*PaginationRequest)(nil),       // 0: explorer.PaginationRequest
	(*BlockRequest)(nil),            // 1: explorer.BlockRequest
	(*BlockNumberRequest)(nil),      // 2: explorer.BlockNumberRequest
	(*BlockCountRequest)(nil),       // 3: explorer.BlockCountRequest
	(*BlockPagination)(nil),         // 4: explorer.BlockPagination
	(*BlockResponse)(nil),           // 5: explorer.BlockResponse
	(*BlockListResponse)(nil),       // 6: explorer.BlockListResponse
	(*TransactionRequest)(nil),      // 7: explorer.TransactionRequest
	(*TransactionResponse)(nil),     // 8: explorer.TransactionResponse
	(*TransactionListResponse)(nil), // 9: explorer.TransactionListResponse
	(*DIDRequest)(nil),              // 10: explorer.DIDRequest
	(*DIDResponse)(nil),             // 11: explorer.DIDResponse
	(*DIDListResponse)(nil),         // 12: explorer.DIDListResponse
	(*StatsResponse)(nil),           // 13: explorer.StatsResponse
	(*ZKBlockTransaction)(nil),      // 14: explorer.ZKBlockTransaction
	nil,                             // 15: explorer.DIDResponse.AttributesEntry
	nil,                             // 16: explorer.StatsResponse.TransactionCountByTypeEntry
	(*timestamp.Timestamp)(nil),     // 17: google.protobuf.Timestamp
	(*empty.Empty)(nil),             // 18: google.protobuf.Empty
}
var file_explorer_proto_depIdxs = []int32{
	14, // 0: explorer.BlockResponse.transactions:type_name -> explorer.ZKBlockTransaction
	5,  // 1: explorer.BlockListResponse.blocks:type_name -> explorer.BlockResponse
	8,  // 2: explorer.TransactionListResponse.transactions:type_name -> explorer.TransactionResponse
	15, // 3: explorer.DIDResponse.attributes:type_name -> explorer.DIDResponse.AttributesEntry
	17, // 4: explorer.DIDResponse.created_at:type_name -> google.protobuf.Timestamp
	17, // 5: explorer.DIDResponse.updated_at:type_name -> google.protobuf.Timestamp
	11, // 6: explorer.DIDListResponse.dids:type_name -> explorer.DIDResponse
	16, // 7: explorer.StatsResponse.transaction_count_by_type:type_name -> explorer.StatsResponse.TransactionCountByTypeEntry
	17, // 8: explorer.StatsResponse.last_updated:type_name -> google.protobuf.Timestamp
	1,  // 9: explorer.ExplorerService.GetBlock:input_type -> explorer.BlockRequest
	2,  // 10: explorer.ExplorerService.GetBlockByNumber:input_type -> explorer.BlockNumberRequest
	4,  // 11: explorer.ExplorerService.ListBlocks:input_type -> explorer.BlockPagination
	3,  // 12: explorer.ExplorerService.GetLatestBlocks:input_type -> explorer.BlockCountRequest
	2,  // 13: explorer.ExplorerService.GetMissingBlocks:input_type -> explorer.BlockNumberRequest
	7,  // 14: explorer.ExplorerService.GetTransaction:input_type -> explorer.TransactionRequest
	2,  // 15: explorer.ExplorerService.ListTransactionsInBlock:input_type -> explorer.BlockNumberRequest
	0,  // 16: explorer.ExplorerService.ListDIDs:input_type -> explorer.PaginationRequest
	10, // 17: explorer.ExplorerService.GetDIDDetails:input_type -> explorer.DIDRequest
	18, // 18: explorer.ExplorerService.GetStats:input_type -> google.protobuf.Empty
	18, // 19: explorer.ExplorerService.StreamBlocks:input_type -> google.protobuf.Empty
	5,  // 20: explorer.ExplorerService.GetBlock:output_type -> explorer.BlockResponse
	5,  // 21: explorer.ExplorerService.GetBlockByNumber:output_type -> explorer.BlockResponse
	6,  // 22: explorer.ExplorerService.ListBlocks:output_type -> explorer.BlockListResponse
	6,  // 23: explorer.ExplorerService.GetLatestBlocks:output_type -> explorer.BlockListResponse
	6,  // 24: explorer.ExplorerService.GetMissingBlocks:output_type -> explorer.BlockListResponse
	8,  // 25: explorer.ExplorerService.GetTransaction:output_type -> explorer.TransactionResponse
	9,  // 26: explorer.ExplorerService.ListTransactionsInBlock:output_type -> explorer.TransactionListResponse
	12, // 27: explorer.ExplorerService.ListDIDs:output_type -> explorer.DIDListResponse
	11, // 28: explorer.ExplorerService.GetDIDDetails:output_type -> explorer.DIDResponse
	13, // 29: explorer.ExplorerService.GetStats:output_type -> explorer.StatsResponse
	5,  // 30: explorer.ExplorerService.StreamBlocks:output_type -> explorer.BlockResponse
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_explorer_proto_init() }
func file_explorer_proto_init() {
	if File_explorer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_explorer_proto_rawDesc), len(file_explorer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_explorer_proto_goTypes,
		DependencyIndexes: file_explorer_proto_depIdxs,
		MessageInfos:      file_explorer_proto_msgTypes,
	}.Build()
	File_explorer_proto = out.File
	file_explorer_proto_goTypes = nil
	file_explorer_proto_depIdxs = nil
}
