// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/mempool.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction represents an Ethereum transaction
type Transaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hash           string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From           string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To             string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value          string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Type           uint32                 `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp      uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId        string                 `protobuf:"bytes,7,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce          uint64                 `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasLimit       string                 `protobuf:"bytes,9,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice       string                 `protobuf:"bytes,10,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	MaxFee         string                 `protobuf:"bytes,11,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"`
	MaxPriorityFee string                 `protobuf:"bytes,12,opt,name=max_priority_fee,json=maxPriorityFee,proto3" json:"max_priority_fee,omitempty"`
	Data           []byte                 `protobuf:"bytes,13,opt,name=data,proto3" json:"data,omitempty"`
	AccessList     []*AccessTuple         `protobuf:"bytes,14,rep,name=access_list,json=accessList,proto3" json:"access_list,omitempty"`
	V              string                 `protobuf:"bytes,15,opt,name=v,proto3" json:"v,omitempty"`
	R              string                 `protobuf:"bytes,16,opt,name=r,proto3" json:"r,omitempty"`
	S              string                 `protobuf:"bytes,17,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_mempool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Transaction) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Transaction) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetGasLimit() string {
	if x != nil {
		return x.GasLimit
	}
	return ""
}

func (x *Transaction) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *Transaction) GetMaxFee() string {
	if x != nil {
		return x.MaxFee
	}
	return ""
}

func (x *Transaction) GetMaxPriorityFee() string {
	if x != nil {
		return x.MaxPriorityFee
	}
	return ""
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction) GetAccessList() []*AccessTuple {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *Transaction) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *Transaction) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *Transaction) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

// AccessTuple is the element type of an access list
type AccessTuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	StorageKeys   []string               `protobuf:"bytes,2,rep,name=storage_keys,json=storageKeys,proto3" json:"storage_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTuple) Reset() {
	*x = AccessTuple{}
	mi := &file_proto_mempool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTuple) ProtoMessage() {}

func (x *AccessTuple) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTuple.ProtoReflect.Descriptor instead.
func (*AccessTuple) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{1}
}

func (x *AccessTuple) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AccessTuple) GetStorageKeys() []string {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

// Metadata contains routing information for mempool transactions
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryNode   bool                   `protobuf:"varint,1,opt,name=primary_node,json=primaryNode,proto3" json:"primary_node,omitempty"`
	ReplicaNode   bool                   `protobuf:"varint,2,opt,name=replica_node,json=replicaNode,proto3" json:"replica_node,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TotalReplicas int32                  `protobuf:"varint,4,opt,name=total_replicas,json=totalReplicas,proto3" json:"total_replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_mempool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetPrimaryNode() bool {
	if x != nil {
		return x.PrimaryNode
	}
	return false
}

func (x *Metadata) GetReplicaNode() bool {
	if x != nil {
		return x.ReplicaNode
	}
	return false
}

func (x *Metadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Metadata) GetTotalReplicas() int32 {
	if x != nil {
		return x.TotalReplicas
	}
	return 0
}

type MempoolTxn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MempoolTxn) Reset() {
	*x = MempoolTxn{}
	mi := &file_proto_mempool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MempoolTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MempoolTxn) ProtoMessage() {}

func (x *MempoolTxn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MempoolTxn.ProtoReflect.Descriptor instead.
func (*MempoolTxn) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{3}
}

func (x *MempoolTxn) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *MempoolTxn) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MempoolTxnBatch represents a batch of mempool transactions
type MempoolTxnBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*MempoolTxn          `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MempoolTxnBatch) Reset() {
	*x = MempoolTxnBatch{}
	mi := &file_proto_mempool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MempoolTxnBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MempoolTxnBatch) ProtoMessage() {}

func (x *MempoolTxnBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MempoolTxnBatch.ProtoReflect.Descriptor instead.
func (*MempoolTxnBatch) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{4}
}

func (x *MempoolTxnBatch) GetTransactions() []*MempoolTxn {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// SubmitResponse is the response for submitting a transaction
type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_proto_mempool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SubmitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SubmitResponseMRE is the response for submitting a transaction
type SubmitResponseMRE struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Hash            string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	MempoolNode     string                 `protobuf:"bytes,4,opt,name=mempool_node,json=mempoolNode,proto3" json:"mempool_node,omitempty"`
	ReplicaMempools []string               `protobuf:"bytes,5,rep,name=replica_mempools,json=replicaMempools,proto3" json:"replica_mempools,omitempty"` // NEW: List of replica mempool IDs
	TotalReplicas   int32                  `protobuf:"varint,6,opt,name=total_replicas,json=totalReplicas,proto3" json:"total_replicas,omitempty"`      // NEW: Total number of replicas (including primary)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitResponseMRE) Reset() {
	*x = SubmitResponseMRE{}
	mi := &file_proto_mempool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponseMRE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponseMRE) ProtoMessage() {}

func (x *SubmitResponseMRE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponseMRE.ProtoReflect.Descriptor instead.
func (*SubmitResponseMRE) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitResponseMRE) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitResponseMRE) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SubmitResponseMRE) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SubmitResponseMRE) GetMempoolNode() string {
	if x != nil {
		return x.MempoolNode
	}
	return ""
}

func (x *SubmitResponseMRE) GetReplicaMempools() []string {
	if x != nil {
		return x.ReplicaMempools
	}
	return nil
}

func (x *SubmitResponseMRE) GetTotalReplicas() int32 {
	if x != nil {
		return x.TotalReplicas
	}
	return 0
}

// BatchSubmitResponse is the response for submitting multiple transactions
type BatchSubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Hashes        []string               `protobuf:"bytes,3,rep,name=hashes,proto3" json:"hashes,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSubmitResponse) Reset() {
	*x = BatchSubmitResponse{}
	mi := &file_proto_mempool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSubmitResponse) ProtoMessage() {}

func (x *BatchSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSubmitResponse.ProtoReflect.Descriptor instead.
func (*BatchSubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{7}
}

func (x *BatchSubmitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchSubmitResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BatchSubmitResponse) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *BatchSubmitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BatchSubmitResponseMRE is the response for submitting multiple transactions
type BatchSubmitResponseMRE struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count          int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Hashes         []string               `protobuf:"bytes,3,rep,name=hashes,proto3" json:"hashes,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ProcessedCount int32                  `protobuf:"varint,5,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"` // NEW: Number of transactions processed
	AcceptedCount  int32                  `protobuf:"varint,6,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`    // NEW: Number of transactions accepted by mempools
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchSubmitResponseMRE) Reset() {
	*x = BatchSubmitResponseMRE{}
	mi := &file_proto_mempool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSubmitResponseMRE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSubmitResponseMRE) ProtoMessage() {}

func (x *BatchSubmitResponseMRE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSubmitResponseMRE.ProtoReflect.Descriptor instead.
func (*BatchSubmitResponseMRE) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{8}
}

func (x *BatchSubmitResponseMRE) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchSubmitResponseMRE) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BatchSubmitResponseMRE) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *BatchSubmitResponseMRE) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BatchSubmitResponseMRE) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *BatchSubmitResponseMRE) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

// GetTransactionByHashRequest is used to request a specific transaction by hash
type GetTransactionByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	FromReplica   bool                   `protobuf:"varint,2,opt,name=from_replica,json=fromReplica,proto3" json:"from_replica,omitempty"` // Optional: search replica database if true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByHashRequest) Reset() {
	*x = GetTransactionByHashRequest{}
	mi := &file_proto_mempool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByHashRequest) ProtoMessage() {}

func (x *GetTransactionByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByHashRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByHashRequest) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransactionByHashRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetTransactionByHashRequest) GetFromReplica() bool {
	if x != nil {
		return x.FromReplica
	}
	return false
}

// TransactionBatch represents a batch of transactions
type TransactionBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionBatch) Reset() {
	*x = TransactionBatch{}
	mi := &file_proto_mempool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBatch) ProtoMessage() {}

func (x *TransactionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBatch.ProtoReflect.Descriptor instead.
func (*TransactionBatch) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionBatch) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// GetTransactionRequest is used to request a specific transaction
type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_proto_mempool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{11}
}

func (x *GetTransactionRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// TransactionLookupResponse contains transaction lookup information
type TransactionLookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	MempoolNode   string                 `protobuf:"bytes,3,opt,name=mempool_node,json=mempoolNode,proto3" json:"mempool_node,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionLookupResponse) Reset() {
	*x = TransactionLookupResponse{}
	mi := &file_proto_mempool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLookupResponse) ProtoMessage() {}

func (x *TransactionLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLookupResponse.ProtoReflect.Descriptor instead.
func (*TransactionLookupResponse) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{12}
}

func (x *TransactionLookupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionLookupResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionLookupResponse) GetMempoolNode() string {
	if x != nil {
		return x.MempoolNode
	}
	return ""
}

func (x *TransactionLookupResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TransactionLookupResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionLookupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TransactionLookupBatch contains multiple transaction lookups
type TransactionLookupBatch struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Success       bool                         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Lookups       []*TransactionLookupResponse `protobuf:"bytes,2,rep,name=lookups,proto3" json:"lookups,omitempty"`
	Count         int32                        `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                       `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionLookupBatch) Reset() {
	*x = TransactionLookupBatch{}
	mi := &file_proto_mempool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLookupBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLookupBatch) ProtoMessage() {}

func (x *TransactionLookupBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLookupBatch.ProtoReflect.Descriptor instead.
func (*TransactionLookupBatch) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{13}
}

func (x *TransactionLookupBatch) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionLookupBatch) GetLookups() []*TransactionLookupResponse {
	if x != nil {
		return x.Lookups
	}
	return nil
}

func (x *TransactionLookupBatch) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TransactionLookupBatch) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetPendingRequest is used to request pending transactions
type GetPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingRequest) Reset() {
	*x = GetPendingRequest{}
	mi := &file_proto_mempool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingRequest) ProtoMessage() {}

func (x *GetPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingRequest.ProtoReflect.Descriptor instead.
func (*GetPendingRequest) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{14}
}

func (x *GetPendingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// CacheStats contains hot cache statistics
type CacheStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CacheSize     int32                  `protobuf:"varint,1,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`
	Hits          uint64                 `protobuf:"varint,2,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses        uint64                 `protobuf:"varint,3,opt,name=misses,proto3" json:"misses,omitempty"`
	Evictions     uint64                 `protobuf:"varint,4,opt,name=evictions,proto3" json:"evictions,omitempty"`
	AverageFee    uint64                 `protobuf:"varint,5,opt,name=average_fee,json=averageFee,proto3" json:"average_fee,omitempty"`
	LastEviction  string                 `protobuf:"bytes,6,opt,name=last_eviction,json=lastEviction,proto3" json:"last_eviction,omitempty"`
	LastUpdate    string                 `protobuf:"bytes,7,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStats) Reset() {
	*x = CacheStats{}
	mi := &file_proto_mempool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStats) ProtoMessage() {}

func (x *CacheStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStats.ProtoReflect.Descriptor instead.
func (*CacheStats) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{15}
}

func (x *CacheStats) GetCacheSize() int32 {
	if x != nil {
		return x.CacheSize
	}
	return 0
}

func (x *CacheStats) GetHits() uint64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *CacheStats) GetMisses() uint64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *CacheStats) GetEvictions() uint64 {
	if x != nil {
		return x.Evictions
	}
	return 0
}

func (x *CacheStats) GetAverageFee() uint64 {
	if x != nil {
		return x.AverageFee
	}
	return 0
}

func (x *CacheStats) GetLastEviction() string {
	if x != nil {
		return x.LastEviction
	}
	return ""
}

func (x *CacheStats) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

// DatabaseStats contains persistent database statistics
type DatabaseStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Transactions         uint64                 `protobuf:"varint,1,opt,name=transactions,proto3" json:"transactions,omitempty"`
	Size                 int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	LsmSize              int64                  `protobuf:"varint,3,opt,name=lsm_size,json=lsmSize,proto3" json:"lsm_size,omitempty"`
	VlogSize             int64                  `protobuf:"varint,4,opt,name=vlog_size,json=vlogSize,proto3" json:"vlog_size,omitempty"`
	LastUpdate           string                 `protobuf:"bytes,5,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	GcRuns               uint64                 `protobuf:"varint,6,opt,name=gc_runs,json=gcRuns,proto3" json:"gc_runs,omitempty"`
	LastGc               string                 `protobuf:"bytes,7,opt,name=last_gc,json=lastGc,proto3" json:"last_gc,omitempty"`
	TotalGcCycles        uint64                 `protobuf:"varint,8,opt,name=total_gc_cycles,json=totalGcCycles,proto3" json:"total_gc_cycles,omitempty"`
	LastGcCycles         uint64                 `protobuf:"varint,9,opt,name=last_gc_cycles,json=lastGcCycles,proto3" json:"last_gc_cycles,omitempty"`
	LastGcDurationMs     uint64                 `protobuf:"varint,10,opt,name=last_gc_duration_ms,json=lastGcDurationMs,proto3" json:"last_gc_duration_ms,omitempty"`
	TotalGcDurationMs    uint64                 `protobuf:"varint,11,opt,name=total_gc_duration_ms,json=totalGcDurationMs,proto3" json:"total_gc_duration_ms,omitempty"`
	FreedSpaceBytes      int64                  `protobuf:"varint,12,opt,name=freed_space_bytes,json=freedSpaceBytes,proto3" json:"freed_space_bytes,omitempty"`
	TotalFreedSpaceBytes int64                  `protobuf:"varint,13,opt,name=total_freed_space_bytes,json=totalFreedSpaceBytes,proto3" json:"total_freed_space_bytes,omitempty"`
	GcThreshold          float32                `protobuf:"fixed32,14,opt,name=gc_threshold,json=gcThreshold,proto3" json:"gc_threshold,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DatabaseStats) Reset() {
	*x = DatabaseStats{}
	mi := &file_proto_mempool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseStats) ProtoMessage() {}

func (x *DatabaseStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseStats.ProtoReflect.Descriptor instead.
func (*DatabaseStats) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{16}
}

func (x *DatabaseStats) GetTransactions() uint64 {
	if x != nil {
		return x.Transactions
	}
	return 0
}

func (x *DatabaseStats) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DatabaseStats) GetLsmSize() int64 {
	if x != nil {
		return x.LsmSize
	}
	return 0
}

func (x *DatabaseStats) GetVlogSize() int64 {
	if x != nil {
		return x.VlogSize
	}
	return 0
}

func (x *DatabaseStats) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

func (x *DatabaseStats) GetGcRuns() uint64 {
	if x != nil {
		return x.GcRuns
	}
	return 0
}

func (x *DatabaseStats) GetLastGc() string {
	if x != nil {
		return x.LastGc
	}
	return ""
}

func (x *DatabaseStats) GetTotalGcCycles() uint64 {
	if x != nil {
		return x.TotalGcCycles
	}
	return 0
}

func (x *DatabaseStats) GetLastGcCycles() uint64 {
	if x != nil {
		return x.LastGcCycles
	}
	return 0
}

func (x *DatabaseStats) GetLastGcDurationMs() uint64 {
	if x != nil {
		return x.LastGcDurationMs
	}
	return 0
}

func (x *DatabaseStats) GetTotalGcDurationMs() uint64 {
	if x != nil {
		return x.TotalGcDurationMs
	}
	return 0
}

func (x *DatabaseStats) GetFreedSpaceBytes() int64 {
	if x != nil {
		return x.FreedSpaceBytes
	}
	return 0
}

func (x *DatabaseStats) GetTotalFreedSpaceBytes() int64 {
	if x != nil {
		return x.TotalFreedSpaceBytes
	}
	return 0
}

func (x *DatabaseStats) GetGcThreshold() float32 {
	if x != nil {
		return x.GcThreshold
	}
	return 0
}

// PrimaryDBStats contains statistics for the primary database
type PrimaryDBStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseStats *DatabaseStats         `protobuf:"bytes,1,opt,name=database_stats,json=databaseStats,proto3" json:"database_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryDBStats) Reset() {
	*x = PrimaryDBStats{}
	mi := &file_proto_mempool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryDBStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryDBStats) ProtoMessage() {}

func (x *PrimaryDBStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryDBStats.ProtoReflect.Descriptor instead.
func (*PrimaryDBStats) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{17}
}

func (x *PrimaryDBStats) GetDatabaseStats() *DatabaseStats {
	if x != nil {
		return x.DatabaseStats
	}
	return nil
}

// ReplicaDBStats contains statistics for the replica database
type ReplicaDBStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseStats *DatabaseStats         `protobuf:"bytes,1,opt,name=database_stats,json=databaseStats,proto3" json:"database_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaDBStats) Reset() {
	*x = ReplicaDBStats{}
	mi := &file_proto_mempool_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaDBStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaDBStats) ProtoMessage() {}

func (x *ReplicaDBStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaDBStats.ProtoReflect.Descriptor instead.
func (*ReplicaDBStats) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{18}
}

func (x *ReplicaDBStats) GetDatabaseStats() *DatabaseStats {
	if x != nil {
		return x.DatabaseStats
	}
	return nil
}

// RoutingStats contains statistics about transaction routing decisions
type RoutingStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryRouted uint64                 `protobuf:"varint,1,opt,name=primary_routed,json=primaryRouted,proto3" json:"primary_routed,omitempty"`
	ReplicaRouted uint64                 `protobuf:"varint,2,opt,name=replica_routed,json=replicaRouted,proto3" json:"replica_routed,omitempty"`
	DefaultRouted uint64                 `protobuf:"varint,3,opt,name=default_routed,json=defaultRouted,proto3" json:"default_routed,omitempty"`
	LastUpdate    string                 `protobuf:"bytes,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingStats) Reset() {
	*x = RoutingStats{}
	mi := &file_proto_mempool_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingStats) ProtoMessage() {}

func (x *RoutingStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingStats.ProtoReflect.Descriptor instead.
func (*RoutingStats) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{19}
}

func (x *RoutingStats) GetPrimaryRouted() uint64 {
	if x != nil {
		return x.PrimaryRouted
	}
	return 0
}

func (x *RoutingStats) GetReplicaRouted() uint64 {
	if x != nil {
		return x.ReplicaRouted
	}
	return 0
}

func (x *RoutingStats) GetDefaultRouted() uint64 {
	if x != nil {
		return x.DefaultRouted
	}
	return 0
}

func (x *RoutingStats) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

// MempoolStats contains comprehensive statistics for dual database mempool
type MempoolStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cache         *CacheStats            `protobuf:"bytes,1,opt,name=cache,proto3" json:"cache,omitempty"`
	Primary       *PrimaryDBStats        `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	Replica       *ReplicaDBStats        `protobuf:"bytes,3,opt,name=replica,proto3" json:"replica,omitempty"`
	Routing       *RoutingStats          `protobuf:"bytes,4,opt,name=routing,proto3" json:"routing,omitempty"`
	LastUpdate    string                 `protobuf:"bytes,5,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MempoolStats) Reset() {
	*x = MempoolStats{}
	mi := &file_proto_mempool_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MempoolStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MempoolStats) ProtoMessage() {}

func (x *MempoolStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MempoolStats.ProtoReflect.Descriptor instead.
func (*MempoolStats) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{20}
}

func (x *MempoolStats) GetCache() *CacheStats {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *MempoolStats) GetPrimary() *PrimaryDBStats {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *MempoolStats) GetReplica() *ReplicaDBStats {
	if x != nil {
		return x.Replica
	}
	return nil
}

func (x *MempoolStats) GetRouting() *RoutingStats {
	if x != nil {
		return x.Routing
	}
	return nil
}

func (x *MempoolStats) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

// MerkleRoots contains individual Merkle roots for each component
type MerkleRoots struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CacheRoot   string                 `protobuf:"bytes,1,opt,name=cache_root,json=cacheRoot,proto3" json:"cache_root,omitempty"`       // Hot cache Merkle root
	PrimaryRoot string                 `protobuf:"bytes,2,opt,name=primary_root,json=primaryRoot,proto3" json:"primary_root,omitempty"` // Primary database Merkle root
	ReplicaRoot string                 `protobuf:"bytes,3,opt,name=replica_root,json=replicaRoot,proto3" json:"replica_root,omitempty"` // Replica database Merkle root
	// Transaction counts for each root
	CacheCount    int32 `protobuf:"varint,5,opt,name=cache_count,json=cacheCount,proto3" json:"cache_count,omitempty"`       // Number of transactions in cache
	PrimaryCount  int32 `protobuf:"varint,6,opt,name=primary_count,json=primaryCount,proto3" json:"primary_count,omitempty"` // Number of transactions in primary DB
	ReplicaCount  int32 `protobuf:"varint,7,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"` // Number of transactions in replica DB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRoots) Reset() {
	*x = MerkleRoots{}
	mi := &file_proto_mempool_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRoots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRoots) ProtoMessage() {}

func (x *MerkleRoots) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRoots.ProtoReflect.Descriptor instead.
func (*MerkleRoots) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{21}
}

func (x *MerkleRoots) GetCacheRoot() string {
	if x != nil {
		return x.CacheRoot
	}
	return ""
}

func (x *MerkleRoots) GetPrimaryRoot() string {
	if x != nil {
		return x.PrimaryRoot
	}
	return ""
}

func (x *MerkleRoots) GetReplicaRoot() string {
	if x != nil {
		return x.ReplicaRoot
	}
	return ""
}

func (x *MerkleRoots) GetCacheCount() int32 {
	if x != nil {
		return x.CacheCount
	}
	return 0
}

func (x *MerkleRoots) GetPrimaryCount() int32 {
	if x != nil {
		return x.PrimaryCount
	}
	return 0
}

func (x *MerkleRoots) GetReplicaCount() int32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

// MerkleRootResponse contains a single Merkle root with metadata
type MerkleRootResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MerkleRoot       string                 `protobuf:"bytes,1,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`                    // The calculated Merkle root
	TransactionCount int32                  `protobuf:"varint,2,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"` // Number of transactions included
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MerkleRootResponse) Reset() {
	*x = MerkleRootResponse{}
	mi := &file_proto_mempool_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRootResponse) ProtoMessage() {}

func (x *MerkleRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRootResponse.ProtoReflect.Descriptor instead.
func (*MerkleRootResponse) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{22}
}

func (x *MerkleRootResponse) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *MerkleRootResponse) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

// FeeSnapshot contains the latest observable state of the fee analyzer
type FeeSnapshot struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Base prices (Wei)
	BaseEnergyWei    string `protobuf:"bytes,2,opt,name=base_energy_wei,json=baseEnergyWei,proto3" json:"base_energy_wei,omitempty"`
	BaseStorageWei   string `protobuf:"bytes,3,opt,name=base_storage_wei,json=baseStorageWei,proto3" json:"base_storage_wei,omitempty"`
	BaseBandwidthWei string `protobuf:"bytes,4,opt,name=base_bandwidth_wei,json=baseBandwidthWei,proto3" json:"base_bandwidth_wei,omitempty"`
	// Utilization metrics
	LastUtilization float64 `protobuf:"fixed64,5,opt,name=last_utilization,json=lastUtilization,proto3" json:"last_utilization,omitempty"`
	// Latest computed fee (Wei)
	LastFeeWei    string `protobuf:"bytes,6,opt,name=last_fee_wei,json=lastFeeWei,proto3" json:"last_fee_wei,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeSnapshot) Reset() {
	*x = FeeSnapshot{}
	mi := &file_proto_mempool_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeSnapshot) ProtoMessage() {}

func (x *FeeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeSnapshot.ProtoReflect.Descriptor instead.
func (*FeeSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{23}
}

func (x *FeeSnapshot) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *FeeSnapshot) GetBaseEnergyWei() string {
	if x != nil {
		return x.BaseEnergyWei
	}
	return ""
}

func (x *FeeSnapshot) GetBaseStorageWei() string {
	if x != nil {
		return x.BaseStorageWei
	}
	return ""
}

func (x *FeeSnapshot) GetBaseBandwidthWei() string {
	if x != nil {
		return x.BaseBandwidthWei
	}
	return ""
}

func (x *FeeSnapshot) GetLastUtilization() float64 {
	if x != nil {
		return x.LastUtilization
	}
	return 0
}

func (x *FeeSnapshot) GetLastFeeWei() string {
	if x != nil {
		return x.LastFeeWei
	}
	return ""
}

// FeeStatistics contains comprehensive fee analysis data
type FeeStatistics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MinFee           uint64                 `protobuf:"varint,1,opt,name=min_fee,json=minFee,proto3" json:"min_fee,omitempty"`
	MaxFee           uint64                 `protobuf:"varint,2,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"`
	MedianFee        uint64                 `protobuf:"varint,3,opt,name=median_fee,json=medianFee,proto3" json:"median_fee,omitempty"`
	MeanFee          uint64                 `protobuf:"varint,4,opt,name=mean_fee,json=meanFee,proto3" json:"mean_fee,omitempty"`
	FeeDistribution  map[string]int32       `protobuf:"bytes,5,rep,name=fee_distribution,json=feeDistribution,proto3" json:"fee_distribution,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PriorityFeeRatio float64                `protobuf:"fixed64,6,opt,name=priority_fee_ratio,json=priorityFeeRatio,proto3" json:"priority_fee_ratio,omitempty"`
	FeeByTxType      map[string]*FeeByType  `protobuf:"bytes,7,rep,name=fee_by_tx_type,json=feeByTxType,proto3" json:"fee_by_tx_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HistoricalTrend  []*FeeTimepoint        `protobuf:"bytes,8,rep,name=historical_trend,json=historicalTrend,proto3" json:"historical_trend,omitempty"`
	RecommendedFees  *RecommendedFees       `protobuf:"bytes,9,opt,name=recommended_fees,json=recommendedFees,proto3" json:"recommended_fees,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeeStatistics) Reset() {
	*x = FeeStatistics{}
	mi := &file_proto_mempool_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeStatistics) ProtoMessage() {}

func (x *FeeStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeStatistics.ProtoReflect.Descriptor instead.
func (*FeeStatistics) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{24}
}

func (x *FeeStatistics) GetMinFee() uint64 {
	if x != nil {
		return x.MinFee
	}
	return 0
}

func (x *FeeStatistics) GetMaxFee() uint64 {
	if x != nil {
		return x.MaxFee
	}
	return 0
}

func (x *FeeStatistics) GetMedianFee() uint64 {
	if x != nil {
		return x.MedianFee
	}
	return 0
}

func (x *FeeStatistics) GetMeanFee() uint64 {
	if x != nil {
		return x.MeanFee
	}
	return 0
}

func (x *FeeStatistics) GetFeeDistribution() map[string]int32 {
	if x != nil {
		return x.FeeDistribution
	}
	return nil
}

func (x *FeeStatistics) GetPriorityFeeRatio() float64 {
	if x != nil {
		return x.PriorityFeeRatio
	}
	return 0
}

func (x *FeeStatistics) GetFeeByTxType() map[string]*FeeByType {
	if x != nil {
		return x.FeeByTxType
	}
	return nil
}

func (x *FeeStatistics) GetHistoricalTrend() []*FeeTimepoint {
	if x != nil {
		return x.HistoricalTrend
	}
	return nil
}

func (x *FeeStatistics) GetRecommendedFees() *RecommendedFees {
	if x != nil {
		return x.RecommendedFees
	}
	return nil
}

// FeeByType contains fee statistics for a specific transaction type
type FeeByType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Mean          uint64                 `protobuf:"varint,2,opt,name=mean,proto3" json:"mean,omitempty"`
	Max           uint64                 `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeByType) Reset() {
	*x = FeeByType{}
	mi := &file_proto_mempool_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeByType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeByType) ProtoMessage() {}

func (x *FeeByType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeByType.ProtoReflect.Descriptor instead.
func (*FeeByType) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{25}
}

func (x *FeeByType) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FeeByType) GetMean() uint64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *FeeByType) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// FeeTimepoint represents a point in fee history
type FeeTimepoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MeanFee       uint64                 `protobuf:"varint,2,opt,name=mean_fee,json=meanFee,proto3" json:"mean_fee,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeTimepoint) Reset() {
	*x = FeeTimepoint{}
	mi := &file_proto_mempool_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeTimepoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeTimepoint) ProtoMessage() {}

func (x *FeeTimepoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeTimepoint.ProtoReflect.Descriptor instead.
func (*FeeTimepoint) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{26}
}

func (x *FeeTimepoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *FeeTimepoint) GetMeanFee() uint64 {
	if x != nil {
		return x.MeanFee
	}
	return 0
}

func (x *FeeTimepoint) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// RecommendedFees contains recommended fee levels
type RecommendedFees struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slow          uint64                 `protobuf:"varint,1,opt,name=slow,proto3" json:"slow,omitempty"`         // ~10min confirmation
	Standard      uint64                 `protobuf:"varint,2,opt,name=standard,proto3" json:"standard,omitempty"` // ~3min confirmation
	Fast          uint64                 `protobuf:"varint,3,opt,name=fast,proto3" json:"fast,omitempty"`         // ~30sec confirmation
	Instant       uint64                 `protobuf:"varint,4,opt,name=instant,proto3" json:"instant,omitempty"`   // Next block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendedFees) Reset() {
	*x = RecommendedFees{}
	mi := &file_proto_mempool_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedFees) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedFees) ProtoMessage() {}

func (x *RecommendedFees) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedFees.ProtoReflect.Descriptor instead.
func (*RecommendedFees) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{27}
}

func (x *RecommendedFees) GetSlow() uint64 {
	if x != nil {
		return x.Slow
	}
	return 0
}

func (x *RecommendedFees) GetStandard() uint64 {
	if x != nil {
		return x.Standard
	}
	return 0
}

func (x *RecommendedFees) GetFast() uint64 {
	if x != nil {
		return x.Fast
	}
	return 0
}

func (x *RecommendedFees) GetInstant() uint64 {
	if x != nil {
		return x.Instant
	}
	return 0
}

type MREStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueCount    int32                  `protobuf:"varint,1,opt,name=queue_count,json=queueCount,proto3" json:"queue_count,omitempty"`
	DbCount       int32                  `protobuf:"varint,2,opt,name=db_count,json=dbCount,proto3" json:"db_count,omitempty"`
	MerkleRoot    string                 `protobuf:"bytes,3,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MREStats) Reset() {
	*x = MREStats{}
	mi := &file_proto_mempool_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MREStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MREStats) ProtoMessage() {}

func (x *MREStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MREStats.ProtoReflect.Descriptor instead.
func (*MREStats) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{28}
}

func (x *MREStats) GetQueueCount() int32 {
	if x != nil {
		return x.QueueCount
	}
	return 0
}

func (x *MREStats) GetDbCount() int32 {
	if x != nil {
		return x.DbCount
	}
	return 0
}

func (x *MREStats) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

type JMDTTransactionData struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // JMDT node identifier
	// Types that are valid to be assigned to TransactionData:
	//
	//	*JMDTTransactionData_SingleTransaction
	//	*JMDTTransactionData_BatchTransactions
	TransactionData isJMDTTransactionData_TransactionData `protobuf_oneof:"transaction_data"`
	Timestamp       string                                `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // When JMDT sent this data
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JMDTTransactionData) Reset() {
	*x = JMDTTransactionData{}
	mi := &file_proto_mempool_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JMDTTransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JMDTTransactionData) ProtoMessage() {}

func (x *JMDTTransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JMDTTransactionData.ProtoReflect.Descriptor instead.
func (*JMDTTransactionData) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{29}
}

func (x *JMDTTransactionData) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JMDTTransactionData) GetTransactionData() isJMDTTransactionData_TransactionData {
	if x != nil {
		return x.TransactionData
	}
	return nil
}

func (x *JMDTTransactionData) GetSingleTransaction() *Transaction {
	if x != nil {
		if x, ok := x.TransactionData.(*JMDTTransactionData_SingleTransaction); ok {
			return x.SingleTransaction
		}
	}
	return nil
}

func (x *JMDTTransactionData) GetBatchTransactions() *TransactionBatch {
	if x != nil {
		if x, ok := x.TransactionData.(*JMDTTransactionData_BatchTransactions); ok {
			return x.BatchTransactions
		}
	}
	return nil
}

func (x *JMDTTransactionData) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type isJMDTTransactionData_TransactionData interface {
	isJMDTTransactionData_TransactionData()
}

type JMDTTransactionData_SingleTransaction struct {
	SingleTransaction *Transaction `protobuf:"bytes,2,opt,name=single_transaction,json=singleTransaction,proto3,oneof"` // Single transaction
}

type JMDTTransactionData_BatchTransactions struct {
	BatchTransactions *TransactionBatch `protobuf:"bytes,3,opt,name=batch_transactions,json=batchTransactions,proto3,oneof"` // Multiple transactions
}

func (*JMDTTransactionData_SingleTransaction) isJMDTTransactionData_TransactionData() {}

func (*JMDTTransactionData_BatchTransactions) isJMDTTransactionData_TransactionData() {}

// Simple acknowledgment response (KEPT for backward compatibility)
type JMDTAcknowledgment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                     // True if all transactions match struct
	ErrorMessage   string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`        // Error details if validation failed
	ProcessedCount int32                  `protobuf:"varint,3,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"` // Number of transactions processed
	AcceptedCount  int32                  `protobuf:"varint,4,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`    // Number of transactions accepted
	InvalidHashes  []string               `protobuf:"bytes,5,rep,name=invalid_hashes,json=invalidHashes,proto3" json:"invalid_hashes,omitempty"`     // Hashes of invalid transactions
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JMDTAcknowledgment) Reset() {
	*x = JMDTAcknowledgment{}
	mi := &file_proto_mempool_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JMDTAcknowledgment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JMDTAcknowledgment) ProtoMessage() {}

func (x *JMDTAcknowledgment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JMDTAcknowledgment.ProtoReflect.Descriptor instead.
func (*JMDTAcknowledgment) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{30}
}

func (x *JMDTAcknowledgment) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JMDTAcknowledgment) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JMDTAcknowledgment) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *JMDTAcknowledgment) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *JMDTAcknowledgment) GetInvalidHashes() []string {
	if x != nil {
		return x.InvalidHashes
	}
	return nil
}

var File_proto_mempool_proto protoreflect.FileDescriptor

const file_proto_mempool_proto_rawDesc = "" +
	"\n" +
	"\x13proto/mempool.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\xae\x03\n" +
	"\vTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x05 \x01(\rR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x19\n" +
	"\bchain_id\x18\a \x01(\tR\achainId\x12\x14\n" +
	"\x05nonce\x18\b \x01(\x04R\x05nonce\x12\x1b\n" +
	"\tgas_limit\x18\t \x01(\tR\bgasLimit\x12\x1b\n" +
	"\tgas_price\x18\n" +
	" \x01(\tR\bgasPrice\x12\x17\n" +
	"\amax_fee\x18\v \x01(\tR\x06maxFee\x12(\n" +
	"\x10max_priority_fee\x18\f \x01(\tR\x0emaxPriorityFee\x12\x12\n" +
	"\x04data\x18\r \x01(\fR\x04data\x123\n" +
	"\vaccess_list\x18\x0e \x03(\v2\x12.proto.AccessTupleR\n" +
	"accessList\x12\f\n" +
	"\x01v\x18\x0f \x01(\tR\x01v\x12\f\n" +
	"\x01r\x18\x10 \x01(\tR\x01r\x12\f\n" +
	"\x01s\x18\x11 \x01(\tR\x01s\"J\n" +
	"\vAccessTuple\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12!\n" +
	"\fstorage_keys\x18\x02 \x03(\tR\vstorageKeys\"\x96\x01\n" +
	"\bMetadata\x12!\n" +
	"\fprimary_node\x18\x01 \x01(\bR\vprimaryNode\x12!\n" +
	"\freplica_node\x18\x02 \x01(\bR\vreplicaNode\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12%\n" +
	"\x0etotal_replicas\x18\x04 \x01(\x05R\rtotalReplicas\"o\n" +
	"\n" +
	"MempoolTxn\x124\n" +
	"\vtransaction\x18\x01 \x01(\v2\x12.proto.TransactionR\vtransaction\x12+\n" +
	"\bmetadata\x18\x02 \x01(\v2\x0f.proto.MetadataR\bmetadata\"H\n" +
	"\x0fMempoolTxnBatch\x125\n" +
	"\ftransactions\x18\x01 \x03(\v2\x11.proto.MempoolTxnR\ftransactions\"T\n" +
	"\x0eSubmitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xcc\x01\n" +
	"\x11SubmitResponseMRE\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12!\n" +
	"\fmempool_node\x18\x04 \x01(\tR\vmempoolNode\x12)\n" +
	"\x10replica_mempools\x18\x05 \x03(\tR\x0freplicaMempools\x12%\n" +
	"\x0etotal_replicas\x18\x06 \x01(\x05R\rtotalReplicas\"s\n" +
	"\x13BatchSubmitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x16\n" +
	"\x06hashes\x18\x03 \x03(\tR\x06hashes\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xc6\x01\n" +
	"\x16BatchSubmitResponseMRE\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x16\n" +
	"\x06hashes\x18\x03 \x03(\tR\x06hashes\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12'\n" +
	"\x0fprocessed_count\x18\x05 \x01(\x05R\x0eprocessedCount\x12%\n" +
	"\x0eaccepted_count\x18\x06 \x01(\x05R\racceptedCount\"T\n" +
	"\x1bGetTransactionByHashRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12!\n" +
	"\ffrom_replica\x18\x02 \x01(\bR\vfromReplica\"J\n" +
	"\x10TransactionBatch\x126\n" +
	"\ftransactions\x18\x01 \x03(\v2\x12.proto.TransactionR\ftransactions\"+\n" +
	"\x15GetTransactionRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xbd\x01\n" +
	"\x19TransactionLookupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12!\n" +
	"\fmempool_node\x18\x03 \x01(\tR\vmempoolNode\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x9a\x01\n" +
	"\x16TransactionLookupBatch\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\alookups\x18\x02 \x03(\v2 .proto.TransactionLookupResponseR\alookups\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\")\n" +
	"\x11GetPendingRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xdc\x01\n" +
	"\n" +
	"CacheStats\x12\x1d\n" +
	"\n" +
	"cache_size\x18\x01 \x01(\x05R\tcacheSize\x12\x12\n" +
	"\x04hits\x18\x02 \x01(\x04R\x04hits\x12\x16\n" +
	"\x06misses\x18\x03 \x01(\x04R\x06misses\x12\x1c\n" +
	"\tevictions\x18\x04 \x01(\x04R\tevictions\x12\x1f\n" +
	"\vaverage_fee\x18\x05 \x01(\x04R\n" +
	"averageFee\x12#\n" +
	"\rlast_eviction\x18\x06 \x01(\tR\flastEviction\x12\x1f\n" +
	"\vlast_update\x18\a \x01(\tR\n" +
	"lastUpdate\"\x86\x04\n" +
	"\rDatabaseStats\x12\"\n" +
	"\ftransactions\x18\x01 \x01(\x04R\ftransactions\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x19\n" +
	"\blsm_size\x18\x03 \x01(\x03R\alsmSize\x12\x1b\n" +
	"\tvlog_size\x18\x04 \x01(\x03R\bvlogSize\x12\x1f\n" +
	"\vlast_update\x18\x05 \x01(\tR\n" +
	"lastUpdate\x12\x17\n" +
	"\agc_runs\x18\x06 \x01(\x04R\x06gcRuns\x12\x17\n" +
	"\alast_gc\x18\a \x01(\tR\x06lastGc\x12&\n" +
	"\x0ftotal_gc_cycles\x18\b \x01(\x04R\rtotalGcCycles\x12$\n" +
	"\x0elast_gc_cycles\x18\t \x01(\x04R\flastGcCycles\x12-\n" +
	"\x13last_gc_duration_ms\x18\n" +
	" \x01(\x04R\x10lastGcDurationMs\x12/\n" +
	"\x14total_gc_duration_ms\x18\v \x01(\x04R\x11totalGcDurationMs\x12*\n" +
	"\x11freed_space_bytes\x18\f \x01(\x03R\x0ffreedSpaceBytes\x125\n" +
	"\x17total_freed_space_bytes\x18\r \x01(\x03R\x14totalFreedSpaceBytes\x12!\n" +
	"\fgc_threshold\x18\x0e \x01(\x02R\vgcThreshold\"M\n" +
	"\x0ePrimaryDBStats\x12;\n" +
	"\x0edatabase_stats\x18\x01 \x01(\v2\x14.proto.DatabaseStatsR\rdatabaseStats\"M\n" +
	"\x0eReplicaDBStats\x12;\n" +
	"\x0edatabase_stats\x18\x01 \x01(\v2\x14.proto.DatabaseStatsR\rdatabaseStats\"\xa4\x01\n" +
	"\fRoutingStats\x12%\n" +
	"\x0eprimary_routed\x18\x01 \x01(\x04R\rprimaryRouted\x12%\n" +
	"\x0ereplica_routed\x18\x02 \x01(\x04R\rreplicaRouted\x12%\n" +
	"\x0edefault_routed\x18\x03 \x01(\x04R\rdefaultRouted\x12\x1f\n" +
	"\vlast_update\x18\x04 \x01(\tR\n" +
	"lastUpdate\"\xe9\x01\n" +
	"\fMempoolStats\x12'\n" +
	"\x05cache\x18\x01 \x01(\v2\x11.proto.CacheStatsR\x05cache\x12/\n" +
	"\aprimary\x18\x02 \x01(\v2\x15.proto.PrimaryDBStatsR\aprimary\x12/\n" +
	"\areplica\x18\x03 \x01(\v2\x15.proto.ReplicaDBStatsR\areplica\x12-\n" +
	"\arouting\x18\x04 \x01(\v2\x13.proto.RoutingStatsR\arouting\x12\x1f\n" +
	"\vlast_update\x18\x05 \x01(\tR\n" +
	"lastUpdate\"\xdd\x01\n" +
	"\vMerkleRoots\x12\x1d\n" +
	"\n" +
	"cache_root\x18\x01 \x01(\tR\tcacheRoot\x12!\n" +
	"\fprimary_root\x18\x02 \x01(\tR\vprimaryRoot\x12!\n" +
	"\freplica_root\x18\x03 \x01(\tR\vreplicaRoot\x12\x1f\n" +
	"\vcache_count\x18\x05 \x01(\x05R\n" +
	"cacheCount\x12#\n" +
	"\rprimary_count\x18\x06 \x01(\x05R\fprimaryCount\x12#\n" +
	"\rreplica_count\x18\a \x01(\x05R\freplicaCount\"b\n" +
	"\x12MerkleRootResponse\x12\x1f\n" +
	"\vmerkle_root\x18\x01 \x01(\tR\n" +
	"merkleRoot\x12+\n" +
	"\x11transaction_count\x18\x02 \x01(\x05R\x10transactionCount\"\xf8\x01\n" +
	"\vFeeSnapshot\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12&\n" +
	"\x0fbase_energy_wei\x18\x02 \x01(\tR\rbaseEnergyWei\x12(\n" +
	"\x10base_storage_wei\x18\x03 \x01(\tR\x0ebaseStorageWei\x12,\n" +
	"\x12base_bandwidth_wei\x18\x04 \x01(\tR\x10baseBandwidthWei\x12)\n" +
	"\x10last_utilization\x18\x05 \x01(\x01R\x0flastUtilization\x12 \n" +
	"\flast_fee_wei\x18\x06 \x01(\tR\n" +
	"lastFeeWei\"\xe4\x04\n" +
	"\rFeeStatistics\x12\x17\n" +
	"\amin_fee\x18\x01 \x01(\x04R\x06minFee\x12\x17\n" +
	"\amax_fee\x18\x02 \x01(\x04R\x06maxFee\x12\x1d\n" +
	"\n" +
	"median_fee\x18\x03 \x01(\x04R\tmedianFee\x12\x19\n" +
	"\bmean_fee\x18\x04 \x01(\x04R\ameanFee\x12T\n" +
	"\x10fee_distribution\x18\x05 \x03(\v2).proto.FeeStatistics.FeeDistributionEntryR\x0ffeeDistribution\x12,\n" +
	"\x12priority_fee_ratio\x18\x06 \x01(\x01R\x10priorityFeeRatio\x12J\n" +
	"\x0efee_by_tx_type\x18\a \x03(\v2%.proto.FeeStatistics.FeeByTxTypeEntryR\vfeeByTxType\x12>\n" +
	"\x10historical_trend\x18\b \x03(\v2\x13.proto.FeeTimepointR\x0fhistoricalTrend\x12A\n" +
	"\x10recommended_fees\x18\t \x01(\v2\x16.proto.RecommendedFeesR\x0frecommendedFees\x1aB\n" +
	"\x14FeeDistributionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aP\n" +
	"\x10FeeByTxTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.proto.FeeByTypeR\x05value:\x028\x01\"G\n" +
	"\tFeeByType\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04mean\x18\x02 \x01(\x04R\x04mean\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x04R\x03max\"]\n" +
	"\fFeeTimepoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x19\n" +
	"\bmean_fee\x18\x02 \x01(\x04R\ameanFee\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"o\n" +
	"\x0fRecommendedFees\x12\x12\n" +
	"\x04slow\x18\x01 \x01(\x04R\x04slow\x12\x1a\n" +
	"\bstandard\x18\x02 \x01(\x04R\bstandard\x12\x12\n" +
	"\x04fast\x18\x03 \x01(\x04R\x04fast\x12\x18\n" +
	"\ainstant\x18\x04 \x01(\x04R\ainstant\"g\n" +
	"\bMREStats\x12\x1f\n" +
	"\vqueue_count\x18\x01 \x01(\x05R\n" +
	"queueCount\x12\x19\n" +
	"\bdb_count\x18\x02 \x01(\x05R\adbCount\x12\x1f\n" +
	"\vmerkle_root\x18\x03 \x01(\tR\n" +
	"merkleRoot\"\xef\x01\n" +
	"\x13JMDTTransactionData\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12C\n" +
	"\x12single_transaction\x18\x02 \x01(\v2\x12.proto.TransactionH\x00R\x11singleTransaction\x12H\n" +
	"\x12batch_transactions\x18\x03 \x01(\v2\x17.proto.TransactionBatchH\x00R\x11batchTransactions\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestampB\x12\n" +
	"\x10transaction_data\"\xca\x01\n" +
	"\x12JMDTAcknowledgment\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12'\n" +
	"\x0fprocessed_count\x18\x03 \x01(\x05R\x0eprocessedCount\x12%\n" +
	"\x0eaccepted_count\x18\x04 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0einvalid_hashes\x18\x05 \x03(\tR\rinvalidHashes2\xa2\x05\n" +
	"\x0eRoutingService\x12A\n" +
	"\x11SubmitTransaction\x12\x12.proto.Transaction\x1a\x18.proto.SubmitResponseMRE\x12I\n" +
	"\x12SubmitTransactions\x12\x17.proto.TransactionBatch\x1a\x1a.proto.BatchSubmitResponse\x12B\n" +
	"\x0eGetTransaction\x12\x1c.proto.GetTransactionRequest\x1a\x12.proto.Transaction\x12K\n" +
	"\x16GetPendingTransactions\x12\x18.proto.GetPendingRequest\x1a\x17.proto.TransactionBatch\x12:\n" +
	"\x0fGetMempoolStats\x12\x16.google.protobuf.Empty\x1a\x0f.proto.MREStats\x12>\n" +
	"\x10GetFeeStatistics\x12\x16.google.protobuf.Empty\x1a\x12.proto.FeeSnapshot\x12V\n" +
	"\x14GetTransactionLookup\x12\x1c.proto.GetTransactionRequest\x1a .proto.TransactionLookupResponse\x12Q\n" +
	"\x18GetAllTransactionLookups\x12\x16.google.protobuf.Empty\x1a\x1d.proto.TransactionLookupBatch\x12J\n" +
	"\x11OnReceiveFromJMDT\x12\x1a.proto.JMDTTransactionData\x1a\x19.proto.JMDTAcknowledgment2\xcd\x05\n" +
	"\x0eMempoolService\x12=\n" +
	"\x11SubmitTransaction\x12\x11.proto.MempoolTxn\x1a\x15.proto.SubmitResponse\x12H\n" +
	"\x12SubmitTransactions\x12\x16.proto.MempoolTxnBatch\x1a\x1a.proto.BatchSubmitResponse\x12M\n" +
	"\x14GetTransactionByHash\x12\".proto.GetTransactionByHashRequest\x1a\x11.proto.MempoolTxn\x12K\n" +
	"\x17PeekPendingTransactions\x12\x18.proto.GetPendingRequest\x1a\x16.proto.MempoolTxnBatch\x12J\n" +
	"\x16GetPendingTransactions\x12\x18.proto.GetPendingRequest\x1a\x16.proto.MempoolTxnBatch\x12I\n" +
	"\x14GetPrimaryMerkleRoot\x12\x16.google.protobuf.Empty\x1a\x19.proto.MerkleRootResponse\x12?\n" +
	"\x11GetAllMerkleRoots\x12\x16.google.protobuf.Empty\x1a\x12.proto.MerkleRoots\x12>\n" +
	"\x0fGetMempoolStats\x12\x16.google.protobuf.Empty\x1a\x13.proto.MempoolStats\x12@\n" +
	"\x10GetFeeStatistics\x12\x16.google.protobuf.Empty\x1a\x14.proto.FeeStatistics\x12<\n" +
	"\x0eGetFeeSnapshot\x12\x16.google.protobuf.Empty\x1a\x12.proto.FeeSnapshotB\tZ\a./protob\x06proto3"

var (
	file_proto_mempool_proto_rawDescOnce sync.Once
	file_proto_mempool_proto_rawDescData []byte
)

func file_proto_mempool_proto_rawDescGZIP() []byte {
	file_proto_mempool_proto_rawDescOnce.Do(func() {
		file_proto_mempool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mempool_proto_rawDesc), len(file_proto_mempool_proto_rawDesc)))
	})
	return file_proto_mempool_proto_rawDescData
}

var file_proto_mempool_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_mempool_proto_goTypes = []any{
	(*Transaction)(nil),                 // 0: proto.Transaction
	(*AccessTuple)(nil),                 // 1: proto.AccessTuple
	(*Metadata)(nil),                    // 2: proto.Metadata
	(*MempoolTxn)(nil),                  // 3: proto.MempoolTxn
	(*MempoolTxnBatch)(nil),             // 4: proto.MempoolTxnBatch
	(*SubmitResponse)(nil),              // 5: proto.SubmitResponse
	(*SubmitResponseMRE)(nil),           // 6: proto.SubmitResponseMRE
	(*BatchSubmitResponse)(nil),         // 7: proto.BatchSubmitResponse
	(*BatchSubmitResponseMRE)(nil),      // 8: proto.BatchSubmitResponseMRE
	(*GetTransactionByHashRequest)(nil), // 9: proto.GetTransactionByHashRequest
	(*TransactionBatch)(nil),            // 10: proto.TransactionBatch
	(*GetTransactionRequest)(nil),       // 11: proto.GetTransactionRequest
	(*TransactionLookupResponse)(nil),   // 12: proto.TransactionLookupResponse
	(*TransactionLookupBatch)(nil),      // 13: proto.TransactionLookupBatch
	(*GetPendingRequest)(nil),           // 14: proto.GetPendingRequest
	(*CacheStats)(nil),                  // 15: proto.CacheStats
	(*DatabaseStats)(nil),               // 16: proto.DatabaseStats
	(*PrimaryDBStats)(nil),              // 17: proto.PrimaryDBStats
	(*ReplicaDBStats)(nil),              // 18: proto.ReplicaDBStats
	(*RoutingStats)(nil),                // 19: proto.RoutingStats
	(*MempoolStats)(nil),                // 20: proto.MempoolStats
	(*MerkleRoots)(nil),                 // 21: proto.MerkleRoots
	(*MerkleRootResponse)(nil),          // 22: proto.MerkleRootResponse
	(*FeeSnapshot)(nil),                 // 23: proto.FeeSnapshot
	(*FeeStatistics)(nil),               // 24: proto.FeeStatistics
	(*FeeByType)(nil),                   // 25: proto.FeeByType
	(*FeeTimepoint)(nil),                // 26: proto.FeeTimepoint
	(*RecommendedFees)(nil),             // 27: proto.RecommendedFees
	(*MREStats)(nil),                    // 28: proto.MREStats
	(*JMDTTransactionData)(nil),         // 29: proto.JMDTTransactionData
	(*JMDTAcknowledgment)(nil),          // 30: proto.JMDTAcknowledgment
	nil,                                 // 31: proto.FeeStatistics.FeeDistributionEntry
	nil,                                 // 32: proto.FeeStatistics.FeeByTxTypeEntry
	(*emptypb.Empty)(nil),               // 33: google.protobuf.Empty
}
var file_proto_mempool_proto_depIdxs = []int32{
	1,  // 0: proto.Transaction.access_list:type_name -> proto.AccessTuple
	0,  // 1: proto.MempoolTxn.transaction:type_name -> proto.Transaction
	2,  // 2: proto.MempoolTxn.metadata:type_name -> proto.Metadata
	3,  // 3: proto.MempoolTxnBatch.transactions:type_name -> proto.MempoolTxn
	0,  // 4: proto.TransactionBatch.transactions:type_name -> proto.Transaction
	12, // 5: proto.TransactionLookupBatch.lookups:type_name -> proto.TransactionLookupResponse
	16, // 6: proto.PrimaryDBStats.database_stats:type_name -> proto.DatabaseStats
	16, // 7: proto.ReplicaDBStats.database_stats:type_name -> proto.DatabaseStats
	15, // 8: proto.MempoolStats.cache:type_name -> proto.CacheStats
	17, // 9: proto.MempoolStats.primary:type_name -> proto.PrimaryDBStats
	18, // 10: proto.MempoolStats.replica:type_name -> proto.ReplicaDBStats
	19, // 11: proto.MempoolStats.routing:type_name -> proto.RoutingStats
	31, // 12: proto.FeeStatistics.fee_distribution:type_name -> proto.FeeStatistics.FeeDistributionEntry
	32, // 13: proto.FeeStatistics.fee_by_tx_type:type_name -> proto.FeeStatistics.FeeByTxTypeEntry
	26, // 14: proto.FeeStatistics.historical_trend:type_name -> proto.FeeTimepoint
	27, // 15: proto.FeeStatistics.recommended_fees:type_name -> proto.RecommendedFees
	0,  // 16: proto.JMDTTransactionData.single_transaction:type_name -> proto.Transaction
	10, // 17: proto.JMDTTransactionData.batch_transactions:type_name -> proto.TransactionBatch
	25, // 18: proto.FeeStatistics.FeeByTxTypeEntry.value:type_name -> proto.FeeByType
	0,  // 19: proto.RoutingService.SubmitTransaction:input_type -> proto.Transaction
	10, // 20: proto.RoutingService.SubmitTransactions:input_type -> proto.TransactionBatch
	11, // 21: proto.RoutingService.GetTransaction:input_type -> proto.GetTransactionRequest
	14, // 22: proto.RoutingService.GetPendingTransactions:input_type -> proto.GetPendingRequest
	33, // 23: proto.RoutingService.GetMempoolStats:input_type -> google.protobuf.Empty
	33, // 24: proto.RoutingService.GetFeeStatistics:input_type -> google.protobuf.Empty
	11, // 25: proto.RoutingService.GetTransactionLookup:input_type -> proto.GetTransactionRequest
	33, // 26: proto.RoutingService.GetAllTransactionLookups:input_type -> google.protobuf.Empty
	29, // 27: proto.RoutingService.OnReceiveFromJMDT:input_type -> proto.JMDTTransactionData
	3,  // 28: proto.MempoolService.SubmitTransaction:input_type -> proto.MempoolTxn
	4,  // 29: proto.MempoolService.SubmitTransactions:input_type -> proto.MempoolTxnBatch
	9,  // 30: proto.MempoolService.GetTransactionByHash:input_type -> proto.GetTransactionByHashRequest
	14, // 31: proto.MempoolService.PeekPendingTransactions:input_type -> proto.GetPendingRequest
	14, // 32: proto.MempoolService.GetPendingTransactions:input_type -> proto.GetPendingRequest
	33, // 33: proto.MempoolService.GetPrimaryMerkleRoot:input_type -> google.protobuf.Empty
	33, // 34: proto.MempoolService.GetAllMerkleRoots:input_type -> google.protobuf.Empty
	33, // 35: proto.MempoolService.GetMempoolStats:input_type -> google.protobuf.Empty
	33, // 36: proto.MempoolService.GetFeeStatistics:input_type -> google.protobuf.Empty
	33, // 37: proto.MempoolService.GetFeeSnapshot:input_type -> google.protobuf.Empty
	6,  // 38: proto.RoutingService.SubmitTransaction:output_type -> proto.SubmitResponseMRE
	7,  // 39: proto.RoutingService.SubmitTransactions:output_type -> proto.BatchSubmitResponse
	0,  // 40: proto.RoutingService.GetTransaction:output_type -> proto.Transaction
	10, // 41: proto.RoutingService.GetPendingTransactions:output_type -> proto.TransactionBatch
	28, // 42: proto.RoutingService.GetMempoolStats:output_type -> proto.MREStats
	23, // 43: proto.RoutingService.GetFeeStatistics:output_type -> proto.FeeSnapshot
	12, // 44: proto.RoutingService.GetTransactionLookup:output_type -> proto.TransactionLookupResponse
	13, // 45: proto.RoutingService.GetAllTransactionLookups:output_type -> proto.TransactionLookupBatch
	30, // 46: proto.RoutingService.OnReceiveFromJMDT:output_type -> proto.JMDTAcknowledgment
	5,  // 47: proto.MempoolService.SubmitTransaction:output_type -> proto.SubmitResponse
	7,  // 48: proto.MempoolService.SubmitTransactions:output_type -> proto.BatchSubmitResponse
	3,  // 49: proto.MempoolService.GetTransactionByHash:output_type -> proto.MempoolTxn
	4,  // 50: proto.MempoolService.PeekPendingTransactions:output_type -> proto.MempoolTxnBatch
	4,  // 51: proto.MempoolService.GetPendingTransactions:output_type -> proto.MempoolTxnBatch
	22, // 52: proto.MempoolService.GetPrimaryMerkleRoot:output_type -> proto.MerkleRootResponse
	21, // 53: proto.MempoolService.GetAllMerkleRoots:output_type -> proto.MerkleRoots
	20, // 54: proto.MempoolService.GetMempoolStats:output_type -> proto.MempoolStats
	24, // 55: proto.MempoolService.GetFeeStatistics:output_type -> proto.FeeStatistics
	23, // 56: proto.MempoolService.GetFeeSnapshot:output_type -> proto.FeeSnapshot
	38, // [38:57] is the sub-list for method output_type
	19, // [19:38] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_mempool_proto_init() }
func file_proto_mempool_proto_init() {
	if File_proto_mempool_proto != nil {
		return
	}
	file_proto_mempool_proto_msgTypes[29].OneofWrappers = []any{
		(*JMDTTransactionData_SingleTransaction)(nil),
		(*JMDTTransactionData_BatchTransactions)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mempool_proto_rawDesc), len(file_proto_mempool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_mempool_proto_goTypes,
		DependencyIndexes: file_proto_mempool_proto_depIdxs,
		MessageInfos:      file_proto_mempool_proto_msgTypes,
	}.Build()
	File_proto_mempool_proto = out.File
	file_proto_mempool_proto_goTypes = nil
	file_proto_mempool_proto_depIdxs = nil
}
