// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: mempool.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MempoolService_SubmitTransaction_FullMethodName      = "/proto.MempoolService/SubmitTransaction"
	MempoolService_SubmitTransactions_FullMethodName     = "/proto.MempoolService/SubmitTransactions"
	MempoolService_GetTransaction_FullMethodName         = "/proto.MempoolService/GetTransaction"
	MempoolService_GetPendingTransactions_FullMethodName = "/proto.MempoolService/GetPendingTransactions"
	MempoolService_GetMempoolStats_FullMethodName        = "/proto.MempoolService/GetMempoolStats"
	MempoolService_GetFeeStatistics_FullMethodName       = "/proto.MempoolService/GetFeeStatistics"
)

// MempoolServiceClient is the client API for MempoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Mempool service definition
type MempoolServiceClient interface {
	// Submit a single transaction to the mempool
	SubmitTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*SubmitResponse, error)
	// Submit multiple transactions to the mempool
	SubmitTransactions(ctx context.Context, in *TransactionBatch, opts ...grpc.CallOption) (*BatchSubmitResponse, error)
	// Get a specific transaction by hash
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	// Get pending transactions with priority ordering
	GetPendingTransactions(ctx context.Context, in *GetPendingRequest, opts ...grpc.CallOption) (*TransactionBatch, error)
	// Get mempool stats
	GetMempoolStats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MempoolStats, error)
	// Get detailed fee statistics
	GetFeeStatistics(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FeeStatistics, error)
}

type mempoolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMempoolServiceClient(cc grpc.ClientConnInterface) MempoolServiceClient {
	return &mempoolServiceClient{cc}
}

func (c *mempoolServiceClient) SubmitTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, MempoolService_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mempoolServiceClient) SubmitTransactions(ctx context.Context, in *TransactionBatch, opts ...grpc.CallOption) (*BatchSubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSubmitResponse)
	err := c.cc.Invoke(ctx, MempoolService_SubmitTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mempoolServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, MempoolService_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mempoolServiceClient) GetPendingTransactions(ctx context.Context, in *GetPendingRequest, opts ...grpc.CallOption) (*TransactionBatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionBatch)
	err := c.cc.Invoke(ctx, MempoolService_GetPendingTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mempoolServiceClient) GetMempoolStats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MempoolStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MempoolStats)
	err := c.cc.Invoke(ctx, MempoolService_GetMempoolStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mempoolServiceClient) GetFeeStatistics(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FeeStatistics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeeStatistics)
	err := c.cc.Invoke(ctx, MempoolService_GetFeeStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MempoolServiceServer is the server API for MempoolService service.
// All implementations must embed UnimplementedMempoolServiceServer
// for forward compatibility.
//
// Mempool service definition
type MempoolServiceServer interface {
	// Submit a single transaction to the mempool
	SubmitTransaction(context.Context, *Transaction) (*SubmitResponse, error)
	// Submit multiple transactions to the mempool
	SubmitTransactions(context.Context, *TransactionBatch) (*BatchSubmitResponse, error)
	// Get a specific transaction by hash
	GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error)
	// Get pending transactions with priority ordering
	GetPendingTransactions(context.Context, *GetPendingRequest) (*TransactionBatch, error)
	// Get mempool stats
	GetMempoolStats(context.Context, *empty.Empty) (*MempoolStats, error)
	// Get detailed fee statistics
	GetFeeStatistics(context.Context, *empty.Empty) (*FeeStatistics, error)
	mustEmbedUnimplementedMempoolServiceServer()
}

// UnimplementedMempoolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMempoolServiceServer struct{}

func (UnimplementedMempoolServiceServer) SubmitTransaction(context.Context, *Transaction) (*SubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedMempoolServiceServer) SubmitTransactions(context.Context, *TransactionBatch) (*BatchSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransactions not implemented")
}
func (UnimplementedMempoolServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedMempoolServiceServer) GetPendingTransactions(context.Context, *GetPendingRequest) (*TransactionBatch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingTransactions not implemented")
}
func (UnimplementedMempoolServiceServer) GetMempoolStats(context.Context, *empty.Empty) (*MempoolStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMempoolStats not implemented")
}
func (UnimplementedMempoolServiceServer) GetFeeStatistics(context.Context, *empty.Empty) (*FeeStatistics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeeStatistics not implemented")
}
func (UnimplementedMempoolServiceServer) mustEmbedUnimplementedMempoolServiceServer() {}
func (UnimplementedMempoolServiceServer) testEmbeddedByValue()                        {}

// UnsafeMempoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MempoolServiceServer will
// result in compilation errors.
type UnsafeMempoolServiceServer interface {
	mustEmbedUnimplementedMempoolServiceServer()
}

func RegisterMempoolServiceServer(s grpc.ServiceRegistrar, srv MempoolServiceServer) {
	// If the following call pancis, it indicates UnimplementedMempoolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MempoolService_ServiceDesc, srv)
}

func _MempoolService_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MempoolServiceServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MempoolService_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MempoolServiceServer).SubmitTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _MempoolService_SubmitTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MempoolServiceServer).SubmitTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MempoolService_SubmitTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MempoolServiceServer).SubmitTransactions(ctx, req.(*TransactionBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _MempoolService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MempoolServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MempoolService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MempoolServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MempoolService_GetPendingTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MempoolServiceServer).GetPendingTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MempoolService_GetPendingTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MempoolServiceServer).GetPendingTransactions(ctx, req.(*GetPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MempoolService_GetMempoolStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MempoolServiceServer).GetMempoolStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MempoolService_GetMempoolStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MempoolServiceServer).GetMempoolStats(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MempoolService_GetFeeStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MempoolServiceServer).GetFeeStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MempoolService_GetFeeStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MempoolServiceServer).GetFeeStatistics(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MempoolService_ServiceDesc is the grpc.ServiceDesc for MempoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MempoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MempoolService",
	HandlerType: (*MempoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _MempoolService_SubmitTransaction_Handler,
		},
		{
			MethodName: "SubmitTransactions",
			Handler:    _MempoolService_SubmitTransactions_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _MempoolService_GetTransaction_Handler,
		},
		{
			MethodName: "GetPendingTransactions",
			Handler:    _MempoolService_GetPendingTransactions_Handler,
		},
		{
			MethodName: "GetMempoolStats",
			Handler:    _MempoolService_GetMempoolStats_Handler,
		},
		{
			MethodName: "GetFeeStatistics",
			Handler:    _MempoolService_GetFeeStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mempool.proto",
}
