// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/mre_lookup.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LookupSource identifies which path inside MRE answered the lookup.
type LookupSource int32

const (
	LookupSource_LOOKUP_SOURCE_UNSPECIFIED LookupSource = 0
	// MRE's Postgres placement index (TxLookup) named a shard.
	LookupSource_LOOKUP_SOURCE_PLACEMENT_INDEX LookupSource = 1
	// MRE fanned out across all primary shard stores.
	LookupSource_LOOKUP_SOURCE_FANOUT LookupSource = 2
	// MRE served a previously conclusive miss from its negative cache.
	LookupSource_LOOKUP_SOURCE_NEGATIVE_CACHE LookupSource = 3
)

// Enum value maps for LookupSource.
var (
	LookupSource_name = map[int32]string{
		0: "LOOKUP_SOURCE_UNSPECIFIED",
		1: "LOOKUP_SOURCE_PLACEMENT_INDEX",
		2: "LOOKUP_SOURCE_FANOUT",
		3: "LOOKUP_SOURCE_NEGATIVE_CACHE",
	}
	LookupSource_value = map[string]int32{
		"LOOKUP_SOURCE_UNSPECIFIED":     0,
		"LOOKUP_SOURCE_PLACEMENT_INDEX": 1,
		"LOOKUP_SOURCE_FANOUT":          2,
		"LOOKUP_SOURCE_NEGATIVE_CACHE":  3,
	}
)

func (x LookupSource) Enum() *LookupSource {
	p := new(LookupSource)
	*p = x
	return p
}

func (x LookupSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LookupSource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mre_lookup_proto_enumTypes[0].Descriptor()
}

func (LookupSource) Type() protoreflect.EnumType {
	return &file_proto_mre_lookup_proto_enumTypes[0]
}

func (x LookupSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LookupSource.Descriptor instead.
func (LookupSource) EnumDescriptor() ([]byte, []int) {
	return file_proto_mre_lookup_proto_rawDescGZIP(), []int{0}
}

// LookupTransactionRequest asks whether a hash is pending anywhere in the
// mempool fleet. The hash is used verbatim by MRE, so send the canonical
// lowercase 0x-prefixed form.
type LookupTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupTransactionRequest) Reset() {
	*x = LookupTransactionRequest{}
	mi := &file_proto_mre_lookup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupTransactionRequest) ProtoMessage() {}

func (x *LookupTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mre_lookup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupTransactionRequest.ProtoReflect.Descriptor instead.
func (*LookupTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mre_lookup_proto_rawDescGZIP(), []int{0}
}

func (x *LookupTransactionRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// LookupTransactionResponse reports the outcome of a non-destructive lookup.
//
// found and degraded MUST be read together:
//
//	found=true                  -> pending on shard_id
//	found=false, degraded=false -> CONCLUSIVE: not pending anywhere
//	found=false, degraded=true  -> INCONCLUSIVE; a shard was unreachable,
//	                               MRE's deadline expired, or its breaker was
//	                               open. Never read this as "absent" and never
//	                               as "pending".
type LookupTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Found bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// Populated only when found=true.
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// Shard that answered; -1 when found=false.
	ShardId int32 `protobuf:"varint,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// Node ID that answered; empty when found=false.
	NodeId        string       `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Source        LookupSource `protobuf:"varint,5,opt,name=source,proto3,enum=proto.LookupSource" json:"source,omitempty"`
	Degraded      bool         `protobuf:"varint,6,opt,name=degraded,proto3" json:"degraded,omitempty"`
	ShardsQueried int32        `protobuf:"varint,7,opt,name=shards_queried,json=shardsQueried,proto3" json:"shards_queried,omitempty"`
	ShardsFailed  int32        `protobuf:"varint,8,opt,name=shards_failed,json=shardsFailed,proto3" json:"shards_failed,omitempty"`
	DurationMs    int64        `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupTransactionResponse) Reset() {
	*x = LookupTransactionResponse{}
	mi := &file_proto_mre_lookup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupTransactionResponse) ProtoMessage() {}

func (x *LookupTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mre_lookup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupTransactionResponse.ProtoReflect.Descriptor instead.
func (*LookupTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mre_lookup_proto_rawDescGZIP(), []int{1}
}

func (x *LookupTransactionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LookupTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *LookupTransactionResponse) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *LookupTransactionResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LookupTransactionResponse) GetSource() LookupSource {
	if x != nil {
		return x.Source
	}
	return LookupSource_LOOKUP_SOURCE_UNSPECIFIED
}

func (x *LookupTransactionResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *LookupTransactionResponse) GetShardsQueried() int32 {
	if x != nil {
		return x.ShardsQueried
	}
	return 0
}

func (x *LookupTransactionResponse) GetShardsFailed() int32 {
	if x != nil {
		return x.ShardsFailed
	}
	return 0
}

func (x *LookupTransactionResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_proto_mre_lookup_proto protoreflect.FileDescriptor

const file_proto_mre_lookup_proto_rawDesc = "" +
	"\n" +
	"\x16proto/mre_lookup.proto\x12\x05proto\x1a\x13proto/mempool.proto\".\n" +
	"\x18LookupTransactionRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xd1\x02\n" +
	"\x19LookupTransactionResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x124\n" +
	"\vtransaction\x18\x02 \x01(\v2\x12.proto.TransactionR\vtransaction\x12\x19\n" +
	"\bshard_id\x18\x03 \x01(\x05R\ashardId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12+\n" +
	"\x06source\x18\x05 \x01(\x0e2\x13.proto.LookupSourceR\x06source\x12\x1a\n" +
	"\bdegraded\x18\x06 \x01(\bR\bdegraded\x12%\n" +
	"\x0eshards_queried\x18\a \x01(\x05R\rshardsQueried\x12#\n" +
	"\rshards_failed\x18\b \x01(\x05R\fshardsFailed\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs*\x8c\x01\n" +
	"\fLookupSource\x12\x1d\n" +
	"\x19LOOKUP_SOURCE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dLOOKUP_SOURCE_PLACEMENT_INDEX\x10\x01\x12\x18\n" +
	"\x14LOOKUP_SOURCE_FANOUT\x10\x02\x12 \n" +
	"\x1cLOOKUP_SOURCE_NEGATIVE_CACHE\x10\x03B\tZ\a./protob\x06proto3"

var (
	file_proto_mre_lookup_proto_rawDescOnce sync.Once
	file_proto_mre_lookup_proto_rawDescData []byte
)

func file_proto_mre_lookup_proto_rawDescGZIP() []byte {
	file_proto_mre_lookup_proto_rawDescOnce.Do(func() {
		file_proto_mre_lookup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mre_lookup_proto_rawDesc), len(file_proto_mre_lookup_proto_rawDesc)))
	})
	return file_proto_mre_lookup_proto_rawDescData
}

var file_proto_mre_lookup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_mre_lookup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mre_lookup_proto_goTypes = []any{
	(LookupSource)(0),                 // 0: proto.LookupSource
	(*LookupTransactionRequest)(nil),  // 1: proto.LookupTransactionRequest
	(*LookupTransactionResponse)(nil), // 2: proto.LookupTransactionResponse
	(*Transaction)(nil),               // 3: proto.Transaction
}
var file_proto_mre_lookup_proto_depIdxs = []int32{
	3, // 0: proto.LookupTransactionResponse.transaction:type_name -> proto.Transaction
	0, // 1: proto.LookupTransactionResponse.source:type_name -> proto.LookupSource
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mre_lookup_proto_init() }
func file_proto_mre_lookup_proto_init() {
	if File_proto_mre_lookup_proto != nil {
		return
	}
	file_proto_mempool_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mre_lookup_proto_rawDesc), len(file_proto_mre_lookup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mre_lookup_proto_goTypes,
		DependencyIndexes: file_proto_mre_lookup_proto_depIdxs,
		EnumInfos:         file_proto_mre_lookup_proto_enumTypes,
		MessageInfos:      file_proto_mre_lookup_proto_msgTypes,
	}.Build()
	File_proto_mre_lookup_proto = out.File
	file_proto_mre_lookup_proto_goTypes = nil
	file_proto_mre_lookup_proto_depIdxs = nil
}
