// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: seednode.proto

package peerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeerDirectory_RegisterPeer_FullMethodName                         = "/peerpb.PeerDirectory/RegisterPeer"
	PeerDirectory_RegisterPeerWithAlias_FullMethodName                = "/peerpb.PeerDirectory/RegisterPeerWithAlias"
	PeerDirectory_UpdatePeer_FullMethodName                           = "/peerpb.PeerDirectory/UpdatePeer"
	PeerDirectory_UpdatePeerWeights_FullMethodName                    = "/peerpb.PeerDirectory/UpdatePeerWeights"
	PeerDirectory_GetPeer_FullMethodName                              = "/peerpb.PeerDirectory/GetPeer"
	PeerDirectory_CreateAlias_FullMethodName                          = "/peerpb.PeerDirectory/CreateAlias"
	PeerDirectory_GetPeerByAlias_FullMethodName                       = "/peerpb.PeerDirectory/GetPeerByAlias"
	PeerDirectory_ListPeers_FullMethodName                            = "/peerpb.PeerDirectory/ListPeers"
	PeerDirectory_SendHeartbeat_FullMethodName                        = "/peerpb.PeerDirectory/SendHeartbeat"
	PeerDirectory_DeleteAlias_FullMethodName                          = "/peerpb.PeerDirectory/DeleteAlias"
	PeerDirectory_DeletePeer_FullMethodName                           = "/peerpb.PeerDirectory/DeletePeer"
	PeerDirectory_HealthCheck_FullMethodName                          = "/peerpb.PeerDirectory/HealthCheck"
	PeerDirectory_AddNeighbor_FullMethodName                          = "/peerpb.PeerDirectory/AddNeighbor"
	PeerDirectory_RemoveNeighbor_FullMethodName                       = "/peerpb.PeerDirectory/RemoveNeighbor"
	PeerDirectory_GetNeighbors_FullMethodName                         = "/peerpb.PeerDirectory/GetNeighbors"
	PeerDirectory_AllocateNeighbors_FullMethodName                    = "/peerpb.PeerDirectory/AllocateNeighbors"
	PeerDirectory_ReportInactiveNeighbor_FullMethodName               = "/peerpb.PeerDirectory/ReportInactiveNeighbor"
	PeerDirectory_CheckPeerHealth_FullMethodName                      = "/peerpb.PeerDirectory/CheckPeerHealth"
	PeerDirectory_GetInactiveNeighborReportsForSubject_FullMethodName = "/peerpb.PeerDirectory/GetInactiveNeighborReportsForSubject"
	PeerDirectory_UpdateBuddy_FullMethodName                          = "/peerpb.PeerDirectory/UpdateBuddy"
	PeerDirectory_ListBuddy_FullMethodName                            = "/peerpb.PeerDirectory/ListBuddy"
	PeerDirectory_RemoveBuddy_FullMethodName                          = "/peerpb.PeerDirectory/RemoveBuddy"
	PeerDirectory_RemoveAllBuddies_FullMethodName                     = "/peerpb.PeerDirectory/RemoveAllBuddies"
)

// PeerDirectoryClient is the client API for PeerDirectory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Peer Directory Service
type PeerDirectoryClient interface {
	RegisterPeer(ctx context.Context, in *RegisterPeerRequest, opts ...grpc.CallOption) (*RegisterPeerResponse, error)
	RegisterPeerWithAlias(ctx context.Context, in *RegisterPeerWithAliasRequest, opts ...grpc.CallOption) (*RegisterPeerWithAliasResponse, error)
	UpdatePeer(ctx context.Context, in *UpdatePeerRequest, opts ...grpc.CallOption) (*UpdatePeerResponse, error)
	UpdatePeerWeights(ctx context.Context, in *UpdatePeerWeightsRequest, opts ...grpc.CallOption) (*UpdatePeerWeightsResponse, error)
	GetPeer(ctx context.Context, in *GetPeerRequest, opts ...grpc.CallOption) (*GetPeerResponse, error)
	CreateAlias(ctx context.Context, in *CreateAliasRequest, opts ...grpc.CallOption) (*CreateAliasResponse, error)
	GetPeerByAlias(ctx context.Context, in *GetPeerByAliasRequest, opts ...grpc.CallOption) (*GetPeerByAliasResponse, error)
	ListPeers(ctx context.Context, in *PeerListRequest, opts ...grpc.CallOption) (*PeerListResponse, error)
	SendHeartbeat(ctx context.Context, in *SendHeartbeatRequest, opts ...grpc.CallOption) (*SendHeartbeatResponse, error)
	DeleteAlias(ctx context.Context, in *DeleteAliasRequest, opts ...grpc.CallOption) (*DeleteAliasResponse, error)
	DeletePeer(ctx context.Context, in *DeletePeerRequest, opts ...grpc.CallOption) (*DeletePeerResponse, error)
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Neighbor management
	AddNeighbor(ctx context.Context, in *AddNeighborRequest, opts ...grpc.CallOption) (*AddNeighborResponse, error)
	RemoveNeighbor(ctx context.Context, in *RemoveNeighborRequest, opts ...grpc.CallOption) (*RemoveNeighborResponse, error)
	GetNeighbors(ctx context.Context, in *GetNeighborsRequest, opts ...grpc.CallOption) (*GetNeighborsResponse, error)
	AllocateNeighbors(ctx context.Context, in *AllocateNeighborsRequest, opts ...grpc.CallOption) (*AllocateNeighborsResponse, error)
	// Inactive neighbor reporting
	ReportInactiveNeighbor(ctx context.Context, in *ReportInactiveNeighborRequest, opts ...grpc.CallOption) (*ReportInactiveNeighborResponse, error)
	// Health check for specific peers
	CheckPeerHealth(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetInactiveNeighborReportsForSubject(ctx context.Context, in *GetInactiveNeighborReportsForSubjectRequest, opts ...grpc.CallOption) (*GetInactiveNeighborReportsForSubjectResponse, error)
	// Buddy management
	UpdateBuddy(ctx context.Context, in *UpdateBuddyRequest, opts ...grpc.CallOption) (*UpdateBuddyResponse, error)
	ListBuddy(ctx context.Context, in *ListBuddyRequest, opts ...grpc.CallOption) (*ListBuddyResponse, error)
	RemoveBuddy(ctx context.Context, in *RemoveBuddyRequest, opts ...grpc.CallOption) (*RemoveBuddyResponse, error)
	RemoveAllBuddies(ctx context.Context, in *RemoveAllBuddiesRequest, opts ...grpc.CallOption) (*RemoveAllBuddiesResponse, error)
}

type peerDirectoryClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerDirectoryClient(cc grpc.ClientConnInterface) PeerDirectoryClient {
	return &peerDirectoryClient{cc}
}

func (c *peerDirectoryClient) RegisterPeer(ctx context.Context, in *RegisterPeerRequest, opts ...grpc.CallOption) (*RegisterPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPeerResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_RegisterPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) RegisterPeerWithAlias(ctx context.Context, in *RegisterPeerWithAliasRequest, opts ...grpc.CallOption) (*RegisterPeerWithAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPeerWithAliasResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_RegisterPeerWithAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) UpdatePeer(ctx context.Context, in *UpdatePeerRequest, opts ...grpc.CallOption) (*UpdatePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePeerResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_UpdatePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) UpdatePeerWeights(ctx context.Context, in *UpdatePeerWeightsRequest, opts ...grpc.CallOption) (*UpdatePeerWeightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePeerWeightsResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_UpdatePeerWeights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) GetPeer(ctx context.Context, in *GetPeerRequest, opts ...grpc.CallOption) (*GetPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeerResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_GetPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) CreateAlias(ctx context.Context, in *CreateAliasRequest, opts ...grpc.CallOption) (*CreateAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAliasResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_CreateAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) GetPeerByAlias(ctx context.Context, in *GetPeerByAliasRequest, opts ...grpc.CallOption) (*GetPeerByAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeerByAliasResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_GetPeerByAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) ListPeers(ctx context.Context, in *PeerListRequest, opts ...grpc.CallOption) (*PeerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerListResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) SendHeartbeat(ctx context.Context, in *SendHeartbeatRequest, opts ...grpc.CallOption) (*SendHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendHeartbeatResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) DeleteAlias(ctx context.Context, in *DeleteAliasRequest, opts ...grpc.CallOption) (*DeleteAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAliasResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_DeleteAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) DeletePeer(ctx context.Context, in *DeletePeerRequest, opts ...grpc.CallOption) (*DeletePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePeerResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_DeletePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PeerDirectory_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) AddNeighbor(ctx context.Context, in *AddNeighborRequest, opts ...grpc.CallOption) (*AddNeighborResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNeighborResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_AddNeighbor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) RemoveNeighbor(ctx context.Context, in *RemoveNeighborRequest, opts ...grpc.CallOption) (*RemoveNeighborResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNeighborResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_RemoveNeighbor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) GetNeighbors(ctx context.Context, in *GetNeighborsRequest, opts ...grpc.CallOption) (*GetNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNeighborsResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_GetNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) AllocateNeighbors(ctx context.Context, in *AllocateNeighborsRequest, opts ...grpc.CallOption) (*AllocateNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateNeighborsResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_AllocateNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) ReportInactiveNeighbor(ctx context.Context, in *ReportInactiveNeighborRequest, opts ...grpc.CallOption) (*ReportInactiveNeighborResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportInactiveNeighborResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_ReportInactiveNeighbor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) CheckPeerHealth(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_CheckPeerHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) GetInactiveNeighborReportsForSubject(ctx context.Context, in *GetInactiveNeighborReportsForSubjectRequest, opts ...grpc.CallOption) (*GetInactiveNeighborReportsForSubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInactiveNeighborReportsForSubjectResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_GetInactiveNeighborReportsForSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) UpdateBuddy(ctx context.Context, in *UpdateBuddyRequest, opts ...grpc.CallOption) (*UpdateBuddyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBuddyResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_UpdateBuddy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) ListBuddy(ctx context.Context, in *ListBuddyRequest, opts ...grpc.CallOption) (*ListBuddyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBuddyResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_ListBuddy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) RemoveBuddy(ctx context.Context, in *RemoveBuddyRequest, opts ...grpc.CallOption) (*RemoveBuddyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBuddyResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_RemoveBuddy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDirectoryClient) RemoveAllBuddies(ctx context.Context, in *RemoveAllBuddiesRequest, opts ...grpc.CallOption) (*RemoveAllBuddiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAllBuddiesResponse)
	err := c.cc.Invoke(ctx, PeerDirectory_RemoveAllBuddies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerDirectoryServer is the server API for PeerDirectory service.
// All implementations must embed UnimplementedPeerDirectoryServer
// for forward compatibility.
//
// Peer Directory Service
type PeerDirectoryServer interface {
	RegisterPeer(context.Context, *RegisterPeerRequest) (*RegisterPeerResponse, error)
	RegisterPeerWithAlias(context.Context, *RegisterPeerWithAliasRequest) (*RegisterPeerWithAliasResponse, error)
	UpdatePeer(context.Context, *UpdatePeerRequest) (*UpdatePeerResponse, error)
	UpdatePeerWeights(context.Context, *UpdatePeerWeightsRequest) (*UpdatePeerWeightsResponse, error)
	GetPeer(context.Context, *GetPeerRequest) (*GetPeerResponse, error)
	CreateAlias(context.Context, *CreateAliasRequest) (*CreateAliasResponse, error)
	GetPeerByAlias(context.Context, *GetPeerByAliasRequest) (*GetPeerByAliasResponse, error)
	ListPeers(context.Context, *PeerListRequest) (*PeerListResponse, error)
	SendHeartbeat(context.Context, *SendHeartbeatRequest) (*SendHeartbeatResponse, error)
	DeleteAlias(context.Context, *DeleteAliasRequest) (*DeleteAliasResponse, error)
	DeletePeer(context.Context, *DeletePeerRequest) (*DeletePeerResponse, error)
	HealthCheck(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Neighbor management
	AddNeighbor(context.Context, *AddNeighborRequest) (*AddNeighborResponse, error)
	RemoveNeighbor(context.Context, *RemoveNeighborRequest) (*RemoveNeighborResponse, error)
	GetNeighbors(context.Context, *GetNeighborsRequest) (*GetNeighborsResponse, error)
	AllocateNeighbors(context.Context, *AllocateNeighborsRequest) (*AllocateNeighborsResponse, error)
	// Inactive neighbor reporting
	ReportInactiveNeighbor(context.Context, *ReportInactiveNeighborRequest) (*ReportInactiveNeighborResponse, error)
	// Health check for specific peers
	CheckPeerHealth(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetInactiveNeighborReportsForSubject(context.Context, *GetInactiveNeighborReportsForSubjectRequest) (*GetInactiveNeighborReportsForSubjectResponse, error)
	// Buddy management
	UpdateBuddy(context.Context, *UpdateBuddyRequest) (*UpdateBuddyResponse, error)
	ListBuddy(context.Context, *ListBuddyRequest) (*ListBuddyResponse, error)
	RemoveBuddy(context.Context, *RemoveBuddyRequest) (*RemoveBuddyResponse, error)
	RemoveAllBuddies(context.Context, *RemoveAllBuddiesRequest) (*RemoveAllBuddiesResponse, error)
	mustEmbedUnimplementedPeerDirectoryServer()
}

// UnimplementedPeerDirectoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerDirectoryServer struct{}

func (UnimplementedPeerDirectoryServer) RegisterPeer(context.Context, *RegisterPeerRequest) (*RegisterPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPeer not implemented")
}
func (UnimplementedPeerDirectoryServer) RegisterPeerWithAlias(context.Context, *RegisterPeerWithAliasRequest) (*RegisterPeerWithAliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPeerWithAlias not implemented")
}
func (UnimplementedPeerDirectoryServer) UpdatePeer(context.Context, *UpdatePeerRequest) (*UpdatePeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePeer not implemented")
}
func (UnimplementedPeerDirectoryServer) UpdatePeerWeights(context.Context, *UpdatePeerWeightsRequest) (*UpdatePeerWeightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePeerWeights not implemented")
}
func (UnimplementedPeerDirectoryServer) GetPeer(context.Context, *GetPeerRequest) (*GetPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeer not implemented")
}
func (UnimplementedPeerDirectoryServer) CreateAlias(context.Context, *CreateAliasRequest) (*CreateAliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlias not implemented")
}
func (UnimplementedPeerDirectoryServer) GetPeerByAlias(context.Context, *GetPeerByAliasRequest) (*GetPeerByAliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeerByAlias not implemented")
}
func (UnimplementedPeerDirectoryServer) ListPeers(context.Context, *PeerListRequest) (*PeerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedPeerDirectoryServer) SendHeartbeat(context.Context, *SendHeartbeatRequest) (*SendHeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedPeerDirectoryServer) DeleteAlias(context.Context, *DeleteAliasRequest) (*DeleteAliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlias not implemented")
}
func (UnimplementedPeerDirectoryServer) DeletePeer(context.Context, *DeletePeerRequest) (*DeletePeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePeer not implemented")
}
func (UnimplementedPeerDirectoryServer) HealthCheck(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPeerDirectoryServer) AddNeighbor(context.Context, *AddNeighborRequest) (*AddNeighborResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNeighbor not implemented")
}
func (UnimplementedPeerDirectoryServer) RemoveNeighbor(context.Context, *RemoveNeighborRequest) (*RemoveNeighborResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNeighbor not implemented")
}
func (UnimplementedPeerDirectoryServer) GetNeighbors(context.Context, *GetNeighborsRequest) (*GetNeighborsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNeighbors not implemented")
}
func (UnimplementedPeerDirectoryServer) AllocateNeighbors(context.Context, *AllocateNeighborsRequest) (*AllocateNeighborsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateNeighbors not implemented")
}
func (UnimplementedPeerDirectoryServer) ReportInactiveNeighbor(context.Context, *ReportInactiveNeighborRequest) (*ReportInactiveNeighborResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportInactiveNeighbor not implemented")
}
func (UnimplementedPeerDirectoryServer) CheckPeerHealth(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPeerHealth not implemented")
}
func (UnimplementedPeerDirectoryServer) GetInactiveNeighborReportsForSubject(context.Context, *GetInactiveNeighborReportsForSubjectRequest) (*GetInactiveNeighborReportsForSubjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInactiveNeighborReportsForSubject not implemented")
}
func (UnimplementedPeerDirectoryServer) UpdateBuddy(context.Context, *UpdateBuddyRequest) (*UpdateBuddyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBuddy not implemented")
}
func (UnimplementedPeerDirectoryServer) ListBuddy(context.Context, *ListBuddyRequest) (*ListBuddyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuddy not implemented")
}
func (UnimplementedPeerDirectoryServer) RemoveBuddy(context.Context, *RemoveBuddyRequest) (*RemoveBuddyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBuddy not implemented")
}
func (UnimplementedPeerDirectoryServer) RemoveAllBuddies(context.Context, *RemoveAllBuddiesRequest) (*RemoveAllBuddiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAllBuddies not implemented")
}
func (UnimplementedPeerDirectoryServer) mustEmbedUnimplementedPeerDirectoryServer() {}
func (UnimplementedPeerDirectoryServer) testEmbeddedByValue()                       {}

// UnsafePeerDirectoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerDirectoryServer will
// result in compilation errors.
type UnsafePeerDirectoryServer interface {
	mustEmbedUnimplementedPeerDirectoryServer()
}

func RegisterPeerDirectoryServer(s grpc.ServiceRegistrar, srv PeerDirectoryServer) {
	// If the following call pancis, it indicates UnimplementedPeerDirectoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerDirectory_ServiceDesc, srv)
}

func _PeerDirectory_RegisterPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).RegisterPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_RegisterPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).RegisterPeer(ctx, req.(*RegisterPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_RegisterPeerWithAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPeerWithAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).RegisterPeerWithAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_RegisterPeerWithAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).RegisterPeerWithAlias(ctx, req.(*RegisterPeerWithAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_UpdatePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).UpdatePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_UpdatePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).UpdatePeer(ctx, req.(*UpdatePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_UpdatePeerWeights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePeerWeightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).UpdatePeerWeights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_UpdatePeerWeights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).UpdatePeerWeights(ctx, req.(*UpdatePeerWeightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_GetPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).GetPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_GetPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).GetPeer(ctx, req.(*GetPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_CreateAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).CreateAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_CreateAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).CreateAlias(ctx, req.(*CreateAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_GetPeerByAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeerByAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).GetPeerByAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_GetPeerByAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).GetPeerByAlias(ctx, req.(*GetPeerByAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).ListPeers(ctx, req.(*PeerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).SendHeartbeat(ctx, req.(*SendHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_DeleteAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).DeleteAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_DeleteAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).DeleteAlias(ctx, req.(*DeleteAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_DeletePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).DeletePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_DeletePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).DeletePeer(ctx, req.(*DeletePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_AddNeighbor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNeighborRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).AddNeighbor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_AddNeighbor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).AddNeighbor(ctx, req.(*AddNeighborRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_RemoveNeighbor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNeighborRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).RemoveNeighbor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_RemoveNeighbor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).RemoveNeighbor(ctx, req.(*RemoveNeighborRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_GetNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).GetNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_GetNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).GetNeighbors(ctx, req.(*GetNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_AllocateNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).AllocateNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_AllocateNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).AllocateNeighbors(ctx, req.(*AllocateNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_ReportInactiveNeighbor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportInactiveNeighborRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).ReportInactiveNeighbor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_ReportInactiveNeighbor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).ReportInactiveNeighbor(ctx, req.(*ReportInactiveNeighborRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_CheckPeerHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).CheckPeerHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_CheckPeerHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).CheckPeerHealth(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_GetInactiveNeighborReportsForSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInactiveNeighborReportsForSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).GetInactiveNeighborReportsForSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_GetInactiveNeighborReportsForSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).GetInactiveNeighborReportsForSubject(ctx, req.(*GetInactiveNeighborReportsForSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_UpdateBuddy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBuddyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).UpdateBuddy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_UpdateBuddy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).UpdateBuddy(ctx, req.(*UpdateBuddyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_ListBuddy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuddyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).ListBuddy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_ListBuddy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).ListBuddy(ctx, req.(*ListBuddyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_RemoveBuddy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBuddyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).RemoveBuddy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_RemoveBuddy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).RemoveBuddy(ctx, req.(*RemoveBuddyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDirectory_RemoveAllBuddies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAllBuddiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDirectoryServer).RemoveAllBuddies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDirectory_RemoveAllBuddies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDirectoryServer).RemoveAllBuddies(ctx, req.(*RemoveAllBuddiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerDirectory_ServiceDesc is the grpc.ServiceDesc for PeerDirectory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerDirectory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peerpb.PeerDirectory",
	HandlerType: (*PeerDirectoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPeer",
			Handler:    _PeerDirectory_RegisterPeer_Handler,
		},
		{
			MethodName: "RegisterPeerWithAlias",
			Handler:    _PeerDirectory_RegisterPeerWithAlias_Handler,
		},
		{
			MethodName: "UpdatePeer",
			Handler:    _PeerDirectory_UpdatePeer_Handler,
		},
		{
			MethodName: "UpdatePeerWeights",
			Handler:    _PeerDirectory_UpdatePeerWeights_Handler,
		},
		{
			MethodName: "GetPeer",
			Handler:    _PeerDirectory_GetPeer_Handler,
		},
		{
			MethodName: "CreateAlias",
			Handler:    _PeerDirectory_CreateAlias_Handler,
		},
		{
			MethodName: "GetPeerByAlias",
			Handler:    _PeerDirectory_GetPeerByAlias_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _PeerDirectory_ListPeers_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _PeerDirectory_SendHeartbeat_Handler,
		},
		{
			MethodName: "DeleteAlias",
			Handler:    _PeerDirectory_DeleteAlias_Handler,
		},
		{
			MethodName: "DeletePeer",
			Handler:    _PeerDirectory_DeletePeer_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PeerDirectory_HealthCheck_Handler,
		},
		{
			MethodName: "AddNeighbor",
			Handler:    _PeerDirectory_AddNeighbor_Handler,
		},
		{
			MethodName: "RemoveNeighbor",
			Handler:    _PeerDirectory_RemoveNeighbor_Handler,
		},
		{
			MethodName: "GetNeighbors",
			Handler:    _PeerDirectory_GetNeighbors_Handler,
		},
		{
			MethodName: "AllocateNeighbors",
			Handler:    _PeerDirectory_AllocateNeighbors_Handler,
		},
		{
			MethodName: "ReportInactiveNeighbor",
			Handler:    _PeerDirectory_ReportInactiveNeighbor_Handler,
		},
		{
			MethodName: "CheckPeerHealth",
			Handler:    _PeerDirectory_CheckPeerHealth_Handler,
		},
		{
			MethodName: "GetInactiveNeighborReportsForSubject",
			Handler:    _PeerDirectory_GetInactiveNeighborReportsForSubject_Handler,
		},
		{
			MethodName: "UpdateBuddy",
			Handler:    _PeerDirectory_UpdateBuddy_Handler,
		},
		{
			MethodName: "ListBuddy",
			Handler:    _PeerDirectory_ListBuddy_Handler,
		},
		{
			MethodName: "RemoveBuddy",
			Handler:    _PeerDirectory_RemoveBuddy_Handler,
		},
		{
			MethodName: "RemoveAllBuddies",
			Handler:    _PeerDirectory_RemoveAllBuddies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seednode.proto",
}
